/**
 * Phase 44 / IPS-01: lazy-load + cache helper for IPS profiles.
 *
 * Mirrors getExtensionProfileForUrl from src/quality/profiles/index.ts
 * (Phase 36 pattern — module-scoped cache + StrictMode-safe in-flight
 * Promise sharing). First call for a URL triggers the dynamic import;
 * subsequent calls hit the cache. Concurrent calls for the same URL
 * share the same in-flight Promise.
 *
 * The IPS_REGISTRY is mounted from src/quality/profiles/ips/index.ts
 * (regenerated by scripts/fetch-ips-profiles.mjs on npm install). The
 * committed JSON is the authoritative offline copy — offline installs
 * pass per RESEARCH §6 Pitfall 8.
 *
 * Plan 44-02 (IPSPanel) will call
 *   `await getIpsProfileForUrl(IPS_COMPOSITION_PROFILE_URL)`
 * before invoking validateIpsBundle().
 */
import type { StructureDefinition } from '@medplum/fhirtypes';
import { IPS_REGISTRY } from './index';

/** Canonical URL of the IPS Composition profile (hl7.fhir.uv.ips@2.0.0). */
export const IPS_COMPOSITION_PROFILE_URL =
  'http://hl7.org/fhir/uv/ips/StructureDefinition/Composition-uv-ips';

const ipsProfileCache = new Map<string, StructureDefinition>();
const ipsProfileInFlight = new Map<
  string,
  Promise<StructureDefinition | null>
>();

export async function getIpsProfileForUrl(
  canonicalUrl: string,
): Promise<StructureDefinition | null> {
  const cached = ipsProfileCache.get(canonicalUrl);
  if (cached !== undefined) return cached;

  const inFlight = ipsProfileInFlight.get(canonicalUrl);
  if (inFlight !== undefined) return inFlight;

  const loader = IPS_REGISTRY[canonicalUrl];
  if (!loader) return null;

  const promise = loader()
    .then((mod) => {
      // Pitfall 1 (RESEARCH §6): dynamic JSON import returns
      // { default: SD }, NOT SD. Static imports auto-unwrap; dynamic
      // imports do not.
      const sd = mod.default;
      ipsProfileCache.set(canonicalUrl, sd);
      ipsProfileInFlight.delete(canonicalUrl);
      return sd;
    })
    .catch((err) => {
      ipsProfileInFlight.delete(canonicalUrl);
      console.warn(
        `[ips] failed to lazy-load ${canonicalUrl}: ${String(err)}`,
      );
      return null;
    });
  ipsProfileInFlight.set(canonicalUrl, promise);
  return promise;
}

/** Test-only hook: drop the cache so subsequent imports re-trigger the loader. */
export function __resetIpsProfileCacheForTests(): void {
  ipsProfileCache.clear();
  ipsProfileInFlight.clear();
}
