// GENERATED by scripts/fetch-ips-profiles.mjs — DO NOT EDIT BY HAND.
// Regenerated on npm install via the 'prepare' lifecycle hook.
// Phase 44: per-URL lazy-load thunks for HL7 IPS profiles.
import type { StructureDefinition } from '@medplum/fhirtypes';

type LazyProfile = () => Promise<{ default: StructureDefinition }>;

export const IPS_REGISTRY: Record<string, LazyProfile> = {
  "http://hl7.org/fhir/uv/ips/StructureDefinition/AllergyIntolerance-uv-ips": () => import('./AllergyIntolerance-allergyintoleranceuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Bundle-uv-ips": () => import('./Bundle-bundleuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/CodeableConcept-uv-ips": () => import('./CodeableConcept-codeableconceptips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Coding-uv-ips": () => import('./Coding-codingips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Composition-uv-ips": () => import('./Composition-compositionuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Condition-uv-ips": () => import('./Condition-conditionuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Device-observer-uv-ips": () => import('./Device-deviceobserveruvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Device-uv-ips": () => import('./Device-deviceuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/DeviceUseStatement-uv-ips": () => import('./DeviceUseStatement-deviceusestatementuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/DiagnosticReport-uv-ips": () => import('./DiagnosticReport-diagnosticreportuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Document": () => import('./httphl7orgfhiruvipsStructureDefinitionDocument-document.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/DocumentSection": () => import('./httphl7orgfhiruvipsStructureDefinitionDocumentSection-documentsection.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Flag-alert-uv-ips": () => import('./Flag-flagalertuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/IPSSectionsLM": () => import('./httphl7orgfhiruvipsStructureDefinitionIPSSectionsLM-ipssectionslm.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/ImagingStudy-uv-ips": () => import('./ImagingStudy-imagingstudyuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Immunization-uv-ips": () => import('./Immunization-immunizationuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Medication-uv-ips": () => import('./Medication-medicationips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/MedicationRequest-uv-ips": () => import('./MedicationRequest-medicationrequestips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/MedicationStatement-uv-ips": () => import('./MedicationStatement-medicationstatementips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-alcoholuse-uv-ips": () => import('./Observation-observationalcoholuseuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-pregnancy-edd-uv-ips": () => import('./Observation-observationpregnancyedduvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-pregnancy-outcome-uv-ips": () => import('./Observation-observationpregnancyoutcomeuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-pregnancy-status-uv-ips": () => import('./Observation-observationpregnancystatusuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-laboratory-pathology-uv-ips": () => import('./Observation-observationresultslaboratorypathologyuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-results-radiology-uv-ips": () => import('./Observation-observationresultsradiologyuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Observation-tobaccouse-uv-ips": () => import('./Observation-observationtobaccouseuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Organization-uv-ips": () => import('./Organization-organizationuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Patient-uv-ips": () => import('./Patient-patientuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Practitioner-uv-ips": () => import('./Practitioner-practitioneruvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/PractitionerRole-uv-ips": () => import('./PractitionerRole-practitionerroleuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Procedure-uv-ips": () => import('./Procedure-procedureuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
  "http://hl7.org/fhir/uv/ips/StructureDefinition/Specimen-uv-ips": () => import('./Specimen-specimenuvips.json') as unknown as Promise<{ default: StructureDefinition }>,
};
