// GENERATED by scripts/fetch-mii-profiles.mjs — DO NOT EDIT BY HAND.
// Regenerated on npm install via the 'prepare' lifecycle hook.
import type { StructureDefinition } from '@medplum/fhirtypes';
import sd0 from './Extension-mii-ex-bildgebung-bildgebungsgrund.json';
import sd1 from './Extension-mii-ex-bildgebung-instanz-details.json';
import sd2 from './Extension-mii-ex-bildgebung-kontrastmittel.json';
import sd3 from './Extension-mii-ex-bildgebung-modalitaet-ct.json';
import sd4 from './Extension-mii-ex-bildgebung-modalitaet-mg-cr-dx.json';
import sd5 from './Extension-mii-ex-bildgebung-modalitaet-mr.json';
import sd6 from './Extension-mii-ex-bildgebung-modalitaet-nm.json';
import sd7 from './Extension-mii-ex-bildgebung-modalitaet-pt.json';
import sd8 from './Extension-mii-ex-bildgebung-modalitaet-us.json';
import sd9 from './Extension-mii-ex-bildgebung-schichtdicke.json';
import sd10 from './Extension-mii-ex-bildgebung-serie-uid.json';
import sd11 from './Extension-mii-ex-bildgebung-sop-instanz-uid.json';
import sd12 from './httpswwwmedizininformatikinitiativedefhirextmodulbildgebungStructureDefinitionLogicalModelBildgebung-mii-lm-bildgebung.json';
import sd13 from './ServiceRequest-mii-pr-bildgebung-anforderung-bildgebung.json';
import sd14 from './CarePlan-mii-pr-bildgebung-behandlungsempfehlung.json';
import sd15 from './Procedure-mii-pr-bildgebung-bildgebungsprozedur.json';
import sd16 from './ImagingStudy-mii-pr-bildgebung-bildgebungsstudie.json';
import sd17 from './Device-mii-pr-bildgebung-geraet.json';
import sd18 from './BodyStructure-mii-pr-bildgebung-koerperstruktur.json';
import sd19 from './MedicationAdministration-mii-pr-bildgebung-kontrastmittelgabe.json';
import sd20 from './Procedure-mii-pr-bildgebung-radiologische-befundungsprozedur.json';
import sd21 from './Observation-mii-pr-bildgebung-radiologische-beobachtung.json';
import sd22 from './DiagnosticReport-mii-pr-bildgebung-radiologischer-befund.json';
import sd23 from './Composition-mii-pr-bildgebung-semistrukt-befundbericht.json';
import sd24 from './httpswwwmedizininformatikinitiativedefhirextmodulbiobankStructureDefinitionLogicalModelBiobank-mii-lm-biobank.json';
import sd25 from './Extension-mii-ex-biobank-anzahl-aliquots.json';
import sd26 from './Extension-mii-ex-biobank-anzahl-passagen.json';
import sd27 from './Extension-mii-ex-biobank-diagnose.json';
import sd28 from './Extension-mii-ex-biobank-ebene.json';
import sd29 from './Extension-mii-ex-biobank-einstellung-blutversorgung.json';
import sd30 from './Extension-mii-ex-biobank-feature-r5.json';
import sd31 from './Extension-mii-ex-biobank-kontaktrolle.json';
import sd32 from './Extension-mii-ex-biobank-kulturprotokoll.json';
import sd33 from './Extension-mii-ex-biobank-modifikationen.json';
import sd34 from './Extension-mii-ex-biobank-temperaturbedingungen.json';
import sd35 from './Extension-mii-ex-biobank-verwaltende-organisation.json';
import sd36 from './Observation-mii-pr-biobank-observation-dna-konzentration.json';
import sd37 from './Observation-mii-pr-biobank-observation-karyotyp.json';
import sd38 from './Observation-mii-pr-biobank-observation-morphologie.json';
import sd39 from './Observation-mii-pr-biobank-observation-proliferation.json';
import sd40 from './Observation-mii-pr-biobank-observation-qualitaetspruefung.json';
import sd41 from './Observation-mii-pr-biobank-observation-wachstumstyp.json';
import sd42 from './Organization-mii-pr-biobank-organization-sammlung-biobank.json';
import sd43 from './Specimen-mii-pr-biobank-specimen-bioprobe-core.json';
import sd44 from './Specimen-mii-pr-biobank-specimen-bioprobe.json';
import sd45 from './Substance-mii-pr-biobank-substance-additiv.json';
import sd46 from './Specimen-mii-pr-biobank-specimen-zellinie-organoid.json';
import sd47 from './Extension-mii-ex-dokument-nlp-processing-status.json';
import sd48 from './DocumentReference-mii-pr-dokument-dokument.json';
import sd49 from './Observation-mii-pr-icu-inspiratorische-sauerstofffraktion-eingestellt.json';
import sd50 from './Observation-mii-pr-icu-bilanz-abnahme-haemofiltration-einzelmesswerte.json';
import sd51 from './Observation-mii-pr-icu-bilanz-ausfuhr-drainage-generisch.json';
import sd52 from './Observation-mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt.json';
import sd53 from './Observation-mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit.json';
import sd54 from './Observation-mii-pr-icu-bilanz-ausfuhr-gallengang.json';
import sd55 from './Observation-mii-pr-icu-bilanz-ausfuhr-magensonde.json';
import sd56 from './Observation-mii-pr-icu-bilanz-ausfuhr-opdrainage.json';
import sd57 from './Observation-mii-pr-icu-bilanz-ausfuhr-pankreasdrainage.json';
import sd58 from './Observation-mii-pr-icu-bilanz-ausfuhr-stuhlgang.json';
import sd59 from './Observation-mii-pr-icu-bilanz-ausfuhr-urin.json';
import sd60 from './Observation-mii-pr-icu-bilanz-ausfuhr-wunddrainage.json';
import sd61 from './Observation-mii-pr-icu-bilanz-blutverlust.json';
import sd62 from './Observation-mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit.json';
import sd63 from './Observation-mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt.json';
import sd64 from './Observation-mii-pr-icu-bilanz-einfuhr-oraler-fluessigkeit.json';
import sd65 from './Observation-mii-pr-icu-bilanz-gesamte-ausfuhr.json';
import sd66 from './Observation-mii-pr-icu-bilanz-gesamte-einfuhr.json';
import sd67 from './Observation-mii-pr-icu-bilanz-gesamte-tages-bilanz.json';
import sd68 from './Observation-mii-pr-icu-bilanz.json';
import sd69 from './Device-mii-pr-icu-device.json';
import sd70 from './Observation-mii-pr-icu-arterieller-druck.json';
import sd71 from './Observation-mii-pr-icu-blutfluss-cardiovasculaeres-geraet.json';
import sd72 from './Observation-mii-pr-icu-blutfluss-extrakorporaler-gasaustausch.json';
import sd73 from './Observation-mii-pr-icu-blutflussindex-extrakorporaler-gasaustausch.json';
import sd74 from './Observation-mii-pr-icu-dauer-extrakorporaler-gasaustausch.json';
import sd75 from './Observation-mii-pr-icu-dauer-haemodialysesitzung.json';
import sd76 from './DeviceMetric-mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-extrakorporale-verfahren.json';
import sd77 from './Procedure-mii-pr-icu-extrakorporales-verfahren.json';
import sd78 from './Observation-mii-pr-icu-gasfluss.json';
import sd79 from './Observation-mii-pr-icu-haemodialyse-blutfluss.json';
import sd80 from './Observation-mii-pr-icu-ionisiertes-kalzium-nierenersatzverfahren.json';
import sd81 from './Observation-mii-pr-icu-parameter-von-extrakorporalen-verfahren.json';
import sd82 from './Observation-mii-pr-icu-substituatfluss.json';
import sd83 from './Observation-mii-pr-icu-substituatvolumen.json';
import sd84 from './Observation-mii-pr-icu-venoeser-druck.json';
import sd85 from './Observation-mii-pr-icu-exspiratorischer-sauerstoffpartialdruck.json';
import sd86 from './Observation-mii-pr-icu-arterieller-blutdruck.json';
import sd87 from './Observation-mii-pr-icu-atemfrequenz.json';
import sd88 from './Observation-mii-pr-icu-herzfrequenz.json';
import sd89 from './Observation-mii-pr-icu-koerpergewicht.json';
import sd90 from './Observation-mii-pr-icu-koerpergroesse.json';
import sd91 from './Observation-mii-pr-icu-kopfumfang.json';
import sd92 from './Observation-mii-pr-icu-atemwegsdruck-bei-null-expiratorischem-gasfluss.json';
import sd93 from './Observation-mii-pr-icu-atemwegsdruck-bei-mittlerem-expiratorischem-gasfluss.json';
import sd94 from './Observation-mii-pr-icu-atemzugvolumen-einstellung.json';
import sd95 from './Observation-mii-pr-icu-atemzugvolumen-waehrend-beatmung.json';
import sd96 from './Procedure-mii-pr-icu-beatmung.json';
import sd97 from './Observation-mii-pr-icu-beatmungsvolumen-pro-minute-maschineller-beatmung.json';
import sd98 from './Observation-mii-pr-icu-beatmungszeit-hohem-druck.json';
import sd99 from './Observation-mii-pr-icu-beatmungszeit-niedrigem-druck.json';
import sd100 from './DeviceMetric-mii-pr-icu-devicemetric-eingestellte-gemessene-parameter-beatmung.json';
import sd101 from './Observation-mii-pr-icu-eingestellter-inspiratorischer-gasfluss.json';
import sd102 from './Observation-mii-pr-icu-einstellung-ausatmungszeit-beatmung.json';
import sd103 from './Observation-mii-pr-icu-einstellung-einatmungszeit-beatmung.json';
import sd104 from './Observation-mii-pr-icu-endexpiratorischer-kohlendioxidpartialdruck.json';
import sd105 from './Observation-mii-pr-icu-exspiratorischer-gasfluss.json';
import sd106 from './Observation-mii-pr-icu-horowitz-in-arteriellem-blut.json';
import sd107 from './Observation-mii-pr-icu-inspiratorische-sauerstofffraktion-gemessen.json';
import sd108 from './Observation-mii-pr-icu-inspiratorischer-gasfluss.json';
import sd109 from './Observation-mii-pr-icu-maximaler-beatmungsdruck.json';
import sd110 from './Observation-mii-pr-icu-mechanische-atemfrequenz-beatmet.json';
import sd111 from './Observation-mii-pr-icu-mittlerer-beatmungsdruck.json';
import sd112 from './Observation-mii-pr-icu-positiv-endexpiratorischer-druck.json';
import sd113 from './Observation-mii-pr-icu-spontane-atemfrequenz-beatmet.json';
import sd114 from './Observation-mii-pr-icu-spontane-mechanische-atemfrequenz-beatmet.json';
import sd115 from './Observation-mii-pr-icu-spontanes-atemzugvolumen.json';
import sd116 from './Observation-mii-pr-icu-spontanes-plus-mechanisches-atemzugvolumen.json';
import sd117 from './Observation-mii-pr-icu-unterstuezungsdruck-beatmung.json';
import sd118 from './Observation-miipr-icu-zeitverhaeltnis-ein-ausatmung.json';
import sd119 from './Observation-mii-pr-icu-dynamische-kompliance.json';
import sd120 from './Observation-mii-pr-icu-parameter-von-beatmung.json';
import sd121 from './Observation-mii-pr-icu-druckdifferenz-beatmung.json';
import sd122 from './httpswwwmedizininformatikinitiativedefhirextmodulicuLogicalModelIntensivmedizin-mii-lm-icu-logicalmodel.json';
import sd123 from './Observation-mii-pr-icu-bilanz-abnahme-haemofiltration-einzelmesswerte.json';
import sd124 from './Observation-mii-pr-icu-bilanz-ausfuhr-drainage-generisch.json';
import sd125 from './Observation-mii-pr-icu-bilanz-ausfuhr-drainage-op.json';
import sd126 from './Observation-mii-pr-icu-bilanz-ausfuhr-drainage-wund.json';
import sd127 from './Observation-mii-pr-icu-bilanz-ausfuhr-fluessigkeit-gesamt.json';
import sd128 from './Observation-mii-pr-icu-bilanz-ausfuhr-gallenfluessigkeit.json';
import sd129 from './Observation-mii-pr-icu-bilanz-ausfuhr-gallengang.json';
import sd130 from './Observation-mii-pr-icu-bilanz-ausfuhr-magensonde.json';
import sd131 from './Observation-mii-pr-icu-bilanz-ausfuhr-opdrainage.json';
import sd132 from './Observation-mii-pr-icu-bilanz-ausfuhr-pankreasdrainage.json';
import sd133 from './Observation-mii-pr-icu-bilanz-ausfuhr-stuhlgang.json';
import sd134 from './Observation-mii-pr-icu-bilanz-ausfuhr-urin.json';
import sd135 from './Observation-mii-pr-icu-bilanz-ausfuhr-wunddrainage.json';
import sd136 from './Observation-mii-pr-icu-bilanz-blutverlust.json';
import sd137 from './Observation-mii-pr-icu-bilanz-einfuhr-enterale-fluesse.json';
import sd138 from './Observation-mii-pr-icu-bilanz-einfuhr-enterale-fluessigkeit.json';
import sd139 from './Observation-mii-pr-icu-bilanz-einfuhr-fluessigkeit-gesamt.json';
import sd140 from './Observation-mii-pr-icu-bilanz-einfuhr-oraler-fluesse.json';
import sd141 from './Observation-mii-pr-icu-bilanz-einfuhr-oraler-fluessigkeit.json';
import sd142 from './Observation-mii-pr-icu-bilanz-gesamte-ausfuhr.json';
import sd143 from './Observation-mii-pr-icu-bilanz-gesamte-einfuhr.json';
import sd144 from './Observation-mii-pr-icu-bilanz-gesamte-tages-bilanz.json';
import sd145 from './Observation-mii-pr-icu-bilanz.json';
import sd146 from './Observation-mii-pr-icu-ect-arterieller-druck.json';
import sd147 from './Observation-mii-pr-icu-ect-blutfluss-cardiovasculaeres-geraet.json';
import sd148 from './Observation-mii-pr-icu-ect-blutfluss-extrakorporaler-gasaustausch.json';
import sd149 from './Observation-mii-pr-icu-ect-blutflussindex-extrakorporaler-gasaustausch.json';
import sd150 from './Observation-mii-pr-icu-ect-dauer-extrakorporaler-gasaustausch.json';
import sd151 from './Observation-mii-pr-icu-ect-dauer-haemodialysesitzung.json';
import sd152 from './DeviceMetric-mii-pr-icu-ect-devicemetric-eingestellte-gemessene-parameter-extrakorporale-verfahren.json';
import sd153 from './Procedure-mii-pr-icu-ect-extrakorporales-verfahren.json';
import sd154 from './Observation-mii-pr-icu-ect-gasfluss.json';
import sd155 from './Observation-mii-pr-icu-ect-haemodialyse-blutfluss.json';
import sd156 from './Observation-mii-pr-icu-ect-ionisiertes-kalzium-nierenersatzverfahren.json';
import sd157 from './Observation-mii-pr-icu-ect-parameter-von-extrakorporalen-verfahren.json';
import sd158 from './Observation-mii-pr-icu-ect-substituatfluss.json';
import sd159 from './Observation-mii-pr-icu-ect-substituatvolumen.json';
import sd160 from './Observation-mii-pr-icu-ect-venoeser-druck.json';
import sd161 from './Device-mii-pr-icu-icu-device.json';
import sd162 from './Observation-mii-pr-icu-muv-arterieller-blutdruck.json';
import sd163 from './Observation-mii-pr-icu-muv-atemfrequenz.json';
import sd164 from './Observation-mii-pr-icu-muv-herzfrequenz.json';
import sd165 from './Observation-mii-pr-icu-muv-koerpergewicht.json';
import sd166 from './Observation-mii-pr-icu-muv-koerpergroesse.json';
import sd167 from './Observation-mii-pr-icu-muv-kopfumfang.json';
import sd168 from './Observation-mii-pr-icu-vent-atemwegsdruck-bei-mitl-exspiratorischem-gasfluss.json';
import sd169 from './Observation-mii-pr-icu-vent-atemwegsdruck-bei-null-exspiratorischem-gasfluss.json';
import sd170 from './Observation-mii-pr-icu-vent-atemzugvolumen-einstellung.json';
import sd171 from './Observation-mii-pr-icu-vent-atemzugvolumen-waehrend-beatmung.json';
import sd172 from './Procedure-mii-pr-icu-vent-beatmung.json';
import sd173 from './Observation-mii-pr-icu-vent-beatmungsvolumen-pro-minute-maschineller.json';
import sd174 from './Observation-mii-pr-icu-vent-beatmungszeit-hohem-druck.json';
import sd175 from './Observation-mii-pr-icu-vent-beatmungszeit-niedrigem-druck.json';
import sd176 from './DeviceMetric-mii-pr-icu-vent-devicemetric-eingestellte-gemessene-parameter-beatmung.json';
import sd177 from './Observation-mii-pr-icu-vent-druckdifferenz-beatmung.json';
import sd178 from './Observation-mii-pr-icu-vent-dynamische-kompliance.json';
import sd179 from './Observation-mii-pr-icu-vent-eingestellter-inspiratorischer-gasfluss.json';
import sd180 from './Observation-mii-pr-icu-vent-einstellung-ausatmungszeit-beatmung.json';
import sd181 from './Observation-mii-pr-icu-vent-einstellung-einatmungszeit-beatmung.json';
import sd182 from './Observation-mii-pr-icu-vent-endexspiratorischer-kohlendioxidpartialdruck.json';
import sd183 from './Observation-mii-pr-icu-vent-exspiratorischer-gasfluss.json';
import sd184 from './Observation-mii-pr-icu-vent-exspiratorischer-sauerstoffpartialdruck.json';
import sd185 from './Observation-mii-pr-icu-vent-horowitz-in-arteriellem-blut.json';
import sd186 from './Observation-mii-pr-icu-vent-inspiratorische-sauerstofffraktion-eingestellt.json';
import sd187 from './Observation-mii-pr-icu-vent-inspiratorische-sauerstofffraktion-gemessen.json';
import sd188 from './Observation-mii-pr-icu-vent-inspiratorische-sauerstofffraktion.json';
import sd189 from './Observation-mii-pr-icu-vent-inspiratorischer-gasfluss.json';
import sd190 from './Observation-mii-pr-icu-vent-maximaler-beatmungsdruck.json';
import sd191 from './Observation-mii-pr-icu-vent-mechanische-atemfrequenz-beatmet.json';
import sd192 from './Observation-mii-pr-icu-vent-mittlerer-beatmungsdruck.json';
import sd193 from './Observation-mii-pr-icu-vent-parameter-von-beatmung.json';
import sd194 from './Observation-mii-pr-icu-vent-positiv-endexspiratorischer-druck.json';
import sd195 from './Observation-mii-pr-icu-vent-spontane-atemfrequenz-beatmet.json';
import sd196 from './Observation-mii-pr-icu-vent-spontane-mechanische-atemfrequenz-beatmet.json';
import sd197 from './Observation-mii-pr-icu-vent-spontanes-atemzugvolumen.json';
import sd198 from './Observation-mii-pr-icu-vent-spontanes-mechanisches-atemzugvolumen-waehrend.json';
import sd199 from './Observation-mii-pr-icu-vent-unterstuezungsdruck-beatmung.json';
import sd200 from './Observation-mii-pr-icu-vent-zeitverhaeltnis-ein-ausatmung.json';
import sd201 from './Observation-mii-pr-kardio-anzahl-kh-aufenthalte-wg-hf.json';
import sd202 from './Observation-mii-pr-kardio-atherosklerotisches-erstereignis.json';
import sd203 from './Device-mii-pr-kardio-device.json';
import sd204 from './Observation-mii-pr-kardio-diagnose-prozedur-nein-unbekannt.json';
import sd205 from './Condition-mii-pr-kardio-diagnose.json';
import sd206 from './Observation-mii-pr-kardio-geraeteprogrammierung.json';
import sd207 from './Procedure-mii-pr-kardio-kardiale-deviceimplantation.json';
import sd208 from './Condition-mii-pr-kardio-klappenvitium.json';
import sd209 from './Observation-mii-pr-kardio-linksventrikulaere-ejektionsfraktion.json';
import sd210 from './DeviceMetric-mii-pr-kardio-nbg-schrittmachermodus.json';
import sd211 from './Observation-mii-pr-kardio-observation-rauchen-acribisalpha.json';
import sd212 from './Observation-mii-pr-kardio-score-modifizierte-rankin-skala.json';
import sd213 from './Observation-mii-pr-kardio-score-nyha.json';
import sd214 from './httpswwwmedizininformatikinitiativedefhirmodulmikrobioStructureDefinitionmiilmmikrobiologicalmodel-mii-lm-mikrobio-logical-model.json';
import sd215 from './httpswwwmedizininformatikinitiativedefhirextmodulmikrobioStructureDefinitionmiilmmikrobiologicalmodel-mii-lm-mikrobio-logical-model.json';
import sd216 from './DiagnosticReport-mii-pr-mikrobio-diagnostic-report.json';
import sd217 from './Observation-mii-pr-mikrobio-empfindlichkeit.json';
import sd218 from './Observation-mii-pr-mikrobio-keimzahl.json';
import sd219 from './Observation-mii-pr-mikrobio-kultur-nachweis.json';
import sd220 from './Observation-mii-pr-mikrobio-mre-klasse.json';
import sd221 from './Observation-mii-pr-mikrobio-mrgn-klasse.json';
import sd222 from './Observation-mii-pr-mikrobio-mikroskopie.json';
import sd223 from './Observation-mii-pr-mikrobio-molekulare-diagnostik.json';
import sd224 from './Observation-mii-pr-mikrobio-resistenzgene.json';
import sd225 from './Observation-mii-pr-mikrobio-resistenzmutation.json';
import sd226 from './Observation-mii-pr-mikrobio-serologie-immunologie.json';
import sd227 from './Observation-mii-pr-mikrobio-virulenzfaktor.json';
import sd228 from './Observation-mii-pr-mikrobio-voraussichtliche-empfindlichkeit.json';
import sd229 from './httpswwwmedizininformatikinitiativedefhirextmodulmolgenStructureDefinitionLogicalModelMolGen-mii-lm-molgen-logicalmodel.json';
import sd230 from './Extension-mii-ex-molgen-empfohlenemassnahme.json';
import sd231 from './Extension-mii-ex-molgen-familiarelinie.json';
import sd232 from './Extension-mii-ex-molgen-riskassessment-einflussfaktor.json';
import sd233 from './Extension-mii-ex-molgen-verwandtschaftsgrad.json';
import sd234 from './Extension-mii-ex-molgen-verwandtschaftsverhaeltnis.json';
import sd235 from './ServiceRequest-mii-pr-molgen-anforderunggenetischertest.json';
import sd236 from './Observation-mii-pr-molgen-diagnostischeimplikation.json';
import sd237 from './Task-mii-pr-molgen-empfohlenefolgemassnahme.json';
import sd238 from './FamilyMemberHistory-mii-pr-molgen-familienanamnese.json';
import sd239 from './Procedure-mii-pr-molgen-genomicstudyanalysis.json';
import sd240 from './Procedure-mii-pr-molgen-genomicstudy.json';
import sd241 from './Observation-mii-pr-molgen-genotyp.json';
import sd242 from './Task-mii-pr-molgen-medikationsempfehlung.json';
import sd243 from './Observation-mii-pr-molgen-mikrosatelliteninstabilitaet.json';
import sd244 from './Observation-mii-pr-molgen-molekularekonsequenz.json';
import sd245 from './Observation-mii-pr-molgen-molekularerbiomarker.json';
import sd246 from './DiagnosticReport-mii-pr-molgen-molekulargenetischerbefundbericht.json';
import sd247 from './Observation-mii-pr-molgen-mutationslast.json';
import sd248 from './RiskAssessment-mii-pr-molgen-polygenerrisikoscore.json';
import sd249 from './Observation-mii-pr-molgen-therapeutischeimplikation.json';
import sd250 from './Observation-mii-pr-molgen-variante.json';
import sd251 from './Device-mii-pr-mtb-genomic-study-device.json';
import sd252 from './Extension-mii-ex-mtb-antrag-kostenuebernahme-antragsstadium.json';
import sd253 from './Extension-mii-ex-mtb-antwort-kostenuebernahme-ablehnungsgrund.json';
import sd254 from './Extension-mii-ex-mtb-antwort-kostenuebernahme-entscheidung.json';
import sd255 from './Extension-mii-ex-mtb-diagnose.json';
import sd256 from './Extension-mii-ex-mtb-empfehlung-evidenzgraduierung.json';
import sd257 from './Extension-mii-ex-mtb-empfehlung-prioritaet.json';
import sd258 from './Extension-mii-ex-mtb-empfehlung-publikation.json';
import sd259 from './Extension-mii-ex-mtb-genomicstudyanalysis-qc.json';
import sd260 from './Extension-mii-ex-mtb-leitlinie-dokumentation.json';
import sd261 from './Extension-mii-ex-mtb-leitlinienbehandlung-status.json';
import sd262 from './Extension-mii-ex-mtb-ngs-bericht-genomic-study.json';
import sd263 from './httpswwwmedizininformatikinitiativedefhirextmodulmtbStructureDefinitionLogicalModelmiilmmtb-mii-lm-mtb.json';
import sd264 from './Claim-mii-pr-mtb-antrag-kostenuebernahme.json';
import sd265 from './ClaimResponse-mii-pr-mtb-antwort-kostenuebernahme.json';
import sd266 from './ClinicalImpression-mii-pr-mtb-behandlungsepisode.json';
import sd267 from './Observation-mii-pr-mtb-biomarker-her2-status.json';
import sd268 from './ServiceRequest-mii-pr-mtb-biopsie-auftrag.json';
import sd269 from './Observation-mii-pr-mtb-brcaness.json';
import sd270 from './Observation-mii-pr-mtb-consent-given.json';
import sd271 from './Observation-mii-pr-mtb-copy-number-variant.json';
import sd272 from './Condition-mii-pr-mtb-diagnose-primaertumor.json';
import sd273 from './Observation-mii-pr-mtb-diagnostische-implikation.json';
import sd274 from './Observation-mii-pr-mtb-dna-fusion.json';
import sd275 from './Observation-mii-pr-mtb-einfache-variante.json';
import sd276 from './ClinicalImpression-mii-pr-mtb-follow-up-clinicalimpression.json';
import sd277 from './Procedure-mii-pr-mtb-genomic-study-analysis.json';
import sd278 from './Procedure-mii-pr-mtb-genomic-study.json';
import sd279 from './ServiceRequest-mii-pr-mtb-histologie-evaluation-auftrag.json';
import sd280 from './Observation-mii-pr-mtb-hrd-score.json';
import sd281 from './ServiceRequest-mii-pr-mtb-humangenetische-beratung-auftrag.json';
import sd282 from './Observation-mii-pr-mtb-immunohistochemistry-her2.json';
import sd283 from './Observation-mii-pr-mtb-immunohistochemistry-mmr.json';
import sd284 from './Observation-mii-pr-mtb-immunohistochemistry-pdl1.json';
import sd285 from './Observation-mii-pr-mtb-immunohistochemistry-phosphorylation.json';
import sd286 from './Observation-mii-pr-mtb-immunohistochemistry.json';
import sd287 from './Observation-mii-pr-mtb-insituhybridization-her2.json';
import sd288 from './Observation-mii-pr-mtb-biomarker-insituhybridization.json';
import sd289 from './Observation-mii-pr-mtb-mikrosatelliteninstabilitaet.json';
import sd290 from './DiagnosticReport-mii-pr-mtb-molecular-pathology-report.json';
import sd291 from './Observation-mii-pr-mtb-molekularer-biomarker.json';
import sd292 from './Observation-mii-pr-mtb-immunohistochemistry-msi.json';
import sd293 from './Observation-mii-pr-mtb-mutationslast.json';
import sd294 from './DiagnosticReport-mii-pr-mtb-ngs-bericht.json';
import sd295 from './Observation-mii-pr-mtb-oncotree.json';
import sd296 from './Observation-mii-pr-mtb-ploidie.json';
import sd297 from './Observation-mii-pr-mtb-response-befund.json';
import sd298 from './Observation-mii-pr-mtb-rna-fusion.json';
import sd299 from './Observation-mii-pr-mtb-rna-seq.json';
import sd300 from './ResearchStudy-mii-pr-mtb-studie.json';
import sd301 from './ServiceRequest-mii-pr-mtb-studieneinschluss-anfrage.json';
import sd302 from './Procedure-mii-pr-mtb-systemische-therapie.json';
import sd303 from './Procedure-mii-pr-mtb-systemische-vortherapie.json';
import sd304 from './MedicationStatement-mii-pr-mtb-systemische-therapie-medication-statement.json';
import sd305 from './Observation-mii-pr-mtb-therapeutische-implikation.json';
import sd306 from './RequestGroup-mii-pr-mtb-therapieempfehlung-kombination.json';
import sd307 from './MedicationRequest-mii-pr-mtb-therapieempfehlung.json';
import sd308 from './CarePlan-mii-pr-mtb-therapieplan.json';
import sd309 from './Observation-mii-pr-mtb-tumorausbreitung.json';
import sd310 from './Observation-mii-pr-mtb-tumorzellgehalt.json';
import sd311 from './Observation-mii-pr-mtb-who-grad-tumor-zns.json';
import sd312 from './Extension-mii-ex-onko-histology-morphology-behavior-icdo3.json';
import sd313 from './Extension-mii-ex-onko-operation-intention.json';
import sd314 from './Extension-mii-ex-onko-operation-urgency.json';
import sd315 from './Extension-mii-ex-onko-strahlentherapie-bestrahlung-boost.json';
import sd316 from './Extension-mii-ex-onko-strahlentherapie-bestrahlung-einzeldosis.json';
import sd317 from './Extension-mii-ex-onko-strahlentherapie-bestrahlung-gesamtdosis.json';
import sd318 from './Extension-mii-ex-onko-strahlentherapie-bestrahlung-seitenlokalisation.json';
import sd319 from './Extension-mii-ex-onko-strahlentherapie-intention.json';
import sd320 from './Extension-mii-ex-onko-strahlentherapie-stellungzurop.json';
import sd321 from './Extension-mii-ex-onko-systemische-therapie-intention.json';
import sd322 from './Extension-mii-ex-onko-systemische-therapie-stellungzurop.json';
import sd323 from './Extension-mii-ex-onko-tnm-cp-praefix.json';
import sd324 from './Extension-mii-ex-onko-tnm-itc-suffix.json';
import sd325 from './Extension-mii-ex-onko-tnm-sn-suffix.json';
import sd326 from './httpswwwmedizininformatikinitiativedefhirextmodulonkoStructureDefinitionLogicalModelmiilmmvgenomseqonkologie-mii-lm-mvgenomseq-onkologie.json';
import sd327 from './httpswwwmedizininformatikinitiativedefhirextmodulonkoStructureDefinitionLogicalModelOrganspezifischeZusatzmodule-mii-lm-onko-organspezifische-zusatzmodule.json';
import sd328 from './httpswwwmedizininformatikinitiativedefhirextmodulonkoStructureDefinitionLogicalModelOnkologie-mii-lm-onko.json';
import sd329 from './Observation-mii-pr-onko-allgemeiner-leistungszustand-ecog.json';
import sd330 from './Observation-mii-pr-onko-allgemeiner-leistungszustand-karnofsky.json';
import sd331 from './Observation-mii-pr-onko-anzahl-befallene-lymphknoten.json';
import sd332 from './Observation-mii-pr-onko-anzahl-befallene-sentinel-lymphknoten.json';
import sd333 from './Observation-mii-pr-onko-anzahl-untersuchte-lymphknoten.json';
import sd334 from './Observation-mii-pr-onko-anzahl-untersuchte-sentinel-lymphknoten.json';
import sd335 from './Observation-mii-pr-onko-asa-klassifikation.json';
import sd336 from './DiagnosticReport-mii-pr-onko-befund.json';
import sd337 from './Condition-mii-pr-onko-diagnose-primaertumor.json';
import sd338 from './Observation-mii-pr-onko-fernmetastasen.json';
import sd339 from './Condition-mii-pr-onko-fruehere-tumorerkrankung.json';
import sd340 from './Observation-mii-pr-onko-genetische-variante.json';
import sd341 from './Observation-mii-pr-onko-grading.json';
import sd342 from './Observation-mii-pr-onko-histologie-icdo3.json';
import sd343 from './Observation-mii-pr-onko-krk-abstand-aboral.json';
import sd344 from './Observation-mii-pr-onko-krk-abstand-anokutan.json';
import sd345 from './Observation-mii-pr-onko-krk-abstand-circumferelle-resektionsebene.json';
import sd346 from './Observation-mii-pr-onko-krk-anastomoseninsuffizienz.json';
import sd347 from './Observation-mii-pr-onko-krk-mrt-mesorektale-faszie.json';
import sd348 from './Procedure-mii-pr-onko-krk-operation.json';
import sd349 from './Specimen-mii-pr-onko-krk-specimen.json';
import sd350 from './Procedure-mii-pr-onko-krk-stoma-markierung.json';
import sd351 from './List-mii-pr-onko-liste-evidenz-erstdiagnose.json';
import sd352 from './Observation-mii-pr-onko-mamma-her2neu-status.json';
import sd353 from './Observation-mii-pr-onko-mamma-menopausenstatus.json';
import sd354 from './Procedure-mii-pr-onko-mamma-operation.json';
import sd355 from './Procedure-mii-pr-onko-mamma-praeoperative-markierung.json';
import sd356 from './Observation-mii-pr-onko-mamma-rezeptorstatus-estrogen.json';
import sd357 from './Observation-mii-pr-onko-mamma-rezeptorstatus-progesteron.json';
import sd358 from './Procedure-mii-pr-onko-mamma-sozialdienst.json';
import sd359 from './Observation-mii-pr-onko-melanom-breslow-tiefe.json';
import sd360 from './Procedure-mii-pr-onko-melanom-exzision.json';
import sd361 from './Observation-mii-pr-onko-melanom-ldh.json';
import sd362 from './Observation-mii-pr-onko-melanom-sicherheitsabstand.json';
import sd363 from './Observation-mii-pr-onko-melanom-ulzeration.json';
import sd364 from './AdverseEvent-mii-pr-onko-nebenwirkung-adverse-event.json';
import sd365 from './Procedure-mii-pr-onko-operation.json';
import sd366 from './Procedure-mii-pr-onko-prostata-operation.json';
import sd367 from './Observation-mii-pr-onko-prostata-anzahl-positive-stanzen.json';
import sd368 from './Observation-mii-pr-onko-prostata-anzahl-stanzen.json';
import sd369 from './Observation-mii-pr-onko-prostata-ca-befall-stanze.json';
import sd370 from './Observation-mii-pr-onko-prostata-clavien-dindo.json';
import sd371 from './Observation-mii-pr-onko-prostata-gleason-grade-group.json';
import sd372 from './Observation-mii-pr-onko-prostata-gleason-pattern.json';
import sd373 from './Observation-mii-pr-onko-prostata-psa.json';
import sd374 from './Observation-mii-pr-onko-residualstatus.json';
import sd375 from './Specimen-mii-pr-onko-specimen.json';
import sd376 from './Procedure-mii-pr-onko-strahlentherapie-bestrahlung-nuklearmedizin.json';
import sd377 from './Procedure-mii-pr-onko-strahlentherapie-bestrahlung-strahlentherapie.json';
import sd378 from './Procedure-mii-pr-onko-strahlentherapie.json';
import sd379 from './Observation-mii-pr-onko-studienteilnahme.json';
import sd380 from './MedicationStatement-mii-pr-onko-systemische-therapie-medikation.json';
import sd381 from './Procedure-mii-pr-onko-systemische-therapie.json';
import sd382 from './RequestGroup-mii-pr-onko-therapieempfehlung-kombinationstherapie.json';
import sd383 from './MedicationRequest-mii-pr-onko-therapieempfehlung-medikation.json';
import sd384 from './ServiceRequest-mii-pr-onko-therapieempfehlung-operation.json';
import sd385 from './Observation-mii-pr-onko-tnm-a-symbol.json';
import sd386 from './Observation-mii-pr-onko-tnm-klassifikation.json';
import sd387 from './Observation-mii-pr-onko-tnm-l-kategorie.json';
import sd388 from './Observation-mii-pr-onko-tnm-m-kategorie.json';
import sd389 from './Observation-mii-pr-onko-tnm-m-symbol.json';
import sd390 from './Observation-mii-pr-onko-tnm-n-kategorie.json';
import sd391 from './Observation-mii-pr-onko-tnm-pn-kategorie.json';
import sd392 from './Observation-mii-pr-onko-tnm-r-symbol.json';
import sd393 from './Observation-mii-pr-onko-tnm-s-kategorie.json';
import sd394 from './Observation-mii-pr-onko-tnm-t-kategorie.json';
import sd395 from './Observation-mii-pr-onko-tnm-v-kategorie.json';
import sd396 from './Observation-mii-pr-onko-tnm-y-symbol.json';
import sd397 from './Observation-mii-pr-onko-tod.json';
import sd398 from './Observation-mii-pr-onko-tumorgroesse.json';
import sd399 from './CarePlan-mii-pr-onko-tumorkonferenz.json';
import sd400 from './Observation-mii-pr-onko-verlauf.json';
import sd401 from './Observation-mii-pr-onko-weitere-klassifikationen.json';
import sd402 from './httpswwwmedizininformatikinitiativedefhirextmodulpathoStructureDefinitionmiilmpathologicalmodel-mii-lm-patho-logical-model.json';
import sd403 from './List-mii-pr-patho-active-problems-list.json';
import sd404 from './Observation-mii-pr-patho-additional-specified-grouper.json';
import sd405 from './Media-mii-pr-patho-attached-image.json';
import sd406 from './Observation-mii-pr-patho-base-observation.json';
import sd407 from './Bundle-mii-pr-patho-bundle.json';
import sd408 from './Composition-mii-pr-patho-composition.json';
import sd409 from './Observation-mii-pr-patho-diagnostic-conclusion-grouper.json';
import sd410 from './Observation-mii-pr-patho-finding.json';
import sd411 from './List-mii-pr-patho-history-of-present-illness.json';
import sd412 from './Observation-mii-pr-patho-intraoperative-grouper.json';
import sd413 from './Observation-mii-pr-patho-macroscopic-grouper.json';
import sd414 from './Observation-mii-pr-patho-microscopic-grouper.json';
import sd415 from './Condition-mii-pr-patho-problem-list-item.json';
import sd416 from './DiagnosticReport-mii-pr-patho-report.json';
import sd417 from './Observation-mii-pr-patho-section-grouper.json';
import sd418 from './ServiceRequest-mii-pr-patho-service-request.json';
import sd419 from './Specimen-mii-pr-patho-specimen.json';
import sd420 from './Extension-mii-pr-pro-questionnaire-capabilities.json';
import sd421 from './Extension-mii-ex-pro-score-score-health-correlation.json';
import sd422 from './httpswwwmedizininformatikinitiativedefhirextmodulproStructureDefinitionmiilmpro-mii-lm-pro.json';
import sd423 from './Observation-mii-pr-pro-depression-t-score.json';
import sd424 from './Observation-mii-pr-pro-observation-bdi-ii.json';
import sd425 from './Observation-mii-pr-pro-observation-eq5d5l-index.json';
import sd426 from './Observation-mii-pr-pro-observation-eq5d5l-profile.json';
import sd427 from './Observation-mii-pr-pro-observation-eq5d5l-vas.json';
import sd428 from './Observation-mii-pr-pro-promis-29-anxiety-tscore.json';
import sd429 from './Observation-mii-pr-pro-promis-29-depression-tscore.json';
import sd430 from './Observation-mii-pr-pro-promis-29-fatigue-tscore.json';
import sd431 from './Observation-mii-pr-pro-promis-29-pain-intensity.json';
import sd432 from './Observation-mii-pr-pro-promis-29-pain-interference-tscore.json';
import sd433 from './Observation-mii-pr-pro-promis-29-physical-function-tscore.json';
import sd434 from './Observation-mii-pr-pro-promis-29-sleep-disturbance-tscore.json';
import sd435 from './Observation-mii-pr-pro-promis-29-social-function-tscore.json';
import sd436 from './Observation-mii-pr-pro-promis-cognitive-function-sf4a-raw-score.json';
import sd437 from './Observation-mii-pr-pro-promis-cognitive-function-sf4a-tscore.json';
import sd438 from './Observation-mii-pr-pro-promis-depression-sf4a-raw-score.json';
import sd439 from './QuestionnaireResponse-mii-pr-pro-questionnaireresponse.json';
import sd440 from './Questionnaire-mii-pr-pro-questionnaire.json';
import sd441 from './ObservationDefinition-mii-pr-pro-score-blueprint.json';
import sd442 from './Observation-mii-pr-pro-score-instance.json';
import sd443 from './Extension-ageofonset.json';
import sd444 from './Extension-mii-ex-seltene-empfehlung-evidenzgraduierung.json';
import sd445 from './Extension-mii-ex-seltene-empfehlung-prioritaet.json';
import sd446 from './Extension-mii-ex-seltene-empfehlung-publikation.json';
import sd447 from './Extension-geneticbasis.json';
import sd448 from './Extension-inheritancepattern.json';
import sd449 from './Extension-penetrance.json';
import sd450 from './Extension-onsetage.json';
import sd451 from './Extension-phenotypicpattern.json';
import sd452 from './Extension-syndromecategory.json';
import sd453 from './httpswwwmedizininformatikinitiativedefhirextmodulselteneStructureDefinitionLogicalModelSeltene-mii-lm-se.json';
import sd454 from './Observation-mii-pr-seltene-blutgruppe.json';
import sd455 from './Observation-mii-pr-seltene-bodymassindex.json';
import sd456 from './Condition-mii-pr-seltene-clinicaldiagnosis.json';
import sd457 from './ClinicalImpression-mii-pr-seltene-clinicalimpression.json';
import sd458 from './FamilyMemberHistory-mii-pr-seltene-familienanamnese.json';
import sd459 from './Condition-mii-pr-seltene-geneticdiagnosis.json';
import sd460 from './Observation-mii-pr-seltene-hpo-assessment.json';
import sd461 from './Observation-mii-pr-seltene-hueftumfang.json';
import sd462 from './Observation-mii-pr-seltene-kopfumfang.json';
import sd463 from './ResearchStudy-mii-pr-seltene-studie.json';
import sd464 from './ServiceRequest-mii-pr-seltene-studieneinschluss-anfrage.json';
import sd465 from './Condition-mii-pr-seltene-symptom-condition.json';
import sd466 from './Observation-mii-pr-seltene-taillenumfang.json';
import sd467 from './Procedure-mii-pr-seltene-therapiedurchgefuehrt.json';
import sd468 from './RequestGroup-mii-pr-seltene-therapieempfehlung-kombination.json';
import sd469 from './ServiceRequest-mii-pr-seltene-therapieempfehlungnichtmedikamentoes.json';
import sd470 from './MedicationRequest-mii-pr-seltene-therapieempfehlung.json';
import sd471 from './CarePlan-mii-pr-seltene-therapieplan.json';
import sd472 from './Extension-vonsebetroffen.json';
import sd473 from './Extension-mii-ex-studie-akronym.json';
import sd474 from './Extension-mii-ex-studie-backport-associatedparty.json';
import sd475 from './Extension-mii-ex-studie-backport-definition-by-combination.json';
import sd476 from './Extension-mii-ex-studie-backport-definition-by-type-and-value.json';
import sd477 from './Extension-mii-ex-studie-backport-definitioncanonical.json';
import sd478 from './Extension-mii-ex-studie-backport-definitionreference.json';
import sd479 from './Extension-mii-ex-studie-backport-label.json';
import sd480 from './Extension-mii-ex-studie-backport-linkid.json';
import sd481 from './Extension-mii-ex-studie-eligibility.json';
import sd482 from './Extension-mii-ex-studie-ethikvotum.json';
import sd483 from './Extension-mii-ex-studie-finanzierung.json';
import sd484 from './Extension-mii-ex-studie-quell-register.json';
import sd485 from './Extension-mii-ex-studie-randomisierungsmethode.json';
import sd486 from './Extension-mii-ex-studie-rekrutierung.json';
import sd487 from './Extension-mii-ex-studie-schlagwort.json';
import sd488 from './Extension-mii-ex-studie-studienfokus.json';
import sd489 from './Extension-mii-ex-studie-studienregister.json';
import sd490 from './httpswwwmedizininformatikinitiativedefhirmodulstudieStructureDefinitionmiilmstudielogicalmodel-mii-lm-studie-logicalmodel.json';
import sd491 from './PractitionerRole-mii-pr-studie-beteiligte-person.json';
import sd492 from './DocumentReference-mii-pr-studie-dokument.json';
import sd493 from './EvidenceVariable-mii-pr-studie-einauschlusskriterium.json';
import sd494 from './ResearchSubject-mii-pr-studie-proband.json';
import sd495 from './Library-mii-pr-studie-register.json';
import sd496 from './ResearchStudy-mii-pr-studie-studie.json';
import sd497 from './ServiceRequest-mii-pr-studie-studieneinschluss-anfrage.json';
import sd498 from './httpswwwmedizininformatikinitiativedefhircoremoduldiagnoseStructureDefinitionLogicalModelSymptom-mii-lm-symptom.json';
import sd499 from './Condition-mii-pr-symptom-condition.json';
import sd500 from './Observation-mii-pr-symptom-observation.json';

export const REGISTRY: Record<string, StructureDefinition> = {
  [(sd0 as unknown as StructureDefinition).url]: sd0 as unknown as StructureDefinition,
  [(sd1 as unknown as StructureDefinition).url]: sd1 as unknown as StructureDefinition,
  [(sd2 as unknown as StructureDefinition).url]: sd2 as unknown as StructureDefinition,
  [(sd3 as unknown as StructureDefinition).url]: sd3 as unknown as StructureDefinition,
  [(sd4 as unknown as StructureDefinition).url]: sd4 as unknown as StructureDefinition,
  [(sd5 as unknown as StructureDefinition).url]: sd5 as unknown as StructureDefinition,
  [(sd6 as unknown as StructureDefinition).url]: sd6 as unknown as StructureDefinition,
  [(sd7 as unknown as StructureDefinition).url]: sd7 as unknown as StructureDefinition,
  [(sd8 as unknown as StructureDefinition).url]: sd8 as unknown as StructureDefinition,
  [(sd9 as unknown as StructureDefinition).url]: sd9 as unknown as StructureDefinition,
  [(sd10 as unknown as StructureDefinition).url]: sd10 as unknown as StructureDefinition,
  [(sd11 as unknown as StructureDefinition).url]: sd11 as unknown as StructureDefinition,
  [(sd12 as unknown as StructureDefinition).url]: sd12 as unknown as StructureDefinition,
  [(sd13 as unknown as StructureDefinition).url]: sd13 as unknown as StructureDefinition,
  [(sd14 as unknown as StructureDefinition).url]: sd14 as unknown as StructureDefinition,
  [(sd15 as unknown as StructureDefinition).url]: sd15 as unknown as StructureDefinition,
  [(sd16 as unknown as StructureDefinition).url]: sd16 as unknown as StructureDefinition,
  [(sd17 as unknown as StructureDefinition).url]: sd17 as unknown as StructureDefinition,
  [(sd18 as unknown as StructureDefinition).url]: sd18 as unknown as StructureDefinition,
  [(sd19 as unknown as StructureDefinition).url]: sd19 as unknown as StructureDefinition,
  [(sd20 as unknown as StructureDefinition).url]: sd20 as unknown as StructureDefinition,
  [(sd21 as unknown as StructureDefinition).url]: sd21 as unknown as StructureDefinition,
  [(sd22 as unknown as StructureDefinition).url]: sd22 as unknown as StructureDefinition,
  [(sd23 as unknown as StructureDefinition).url]: sd23 as unknown as StructureDefinition,
  [(sd24 as unknown as StructureDefinition).url]: sd24 as unknown as StructureDefinition,
  [(sd25 as unknown as StructureDefinition).url]: sd25 as unknown as StructureDefinition,
  [(sd26 as unknown as StructureDefinition).url]: sd26 as unknown as StructureDefinition,
  [(sd27 as unknown as StructureDefinition).url]: sd27 as unknown as StructureDefinition,
  [(sd28 as unknown as StructureDefinition).url]: sd28 as unknown as StructureDefinition,
  [(sd29 as unknown as StructureDefinition).url]: sd29 as unknown as StructureDefinition,
  [(sd30 as unknown as StructureDefinition).url]: sd30 as unknown as StructureDefinition,
  [(sd31 as unknown as StructureDefinition).url]: sd31 as unknown as StructureDefinition,
  [(sd32 as unknown as StructureDefinition).url]: sd32 as unknown as StructureDefinition,
  [(sd33 as unknown as StructureDefinition).url]: sd33 as unknown as StructureDefinition,
  [(sd34 as unknown as StructureDefinition).url]: sd34 as unknown as StructureDefinition,
  [(sd35 as unknown as StructureDefinition).url]: sd35 as unknown as StructureDefinition,
  [(sd36 as unknown as StructureDefinition).url]: sd36 as unknown as StructureDefinition,
  [(sd37 as unknown as StructureDefinition).url]: sd37 as unknown as StructureDefinition,
  [(sd38 as unknown as StructureDefinition).url]: sd38 as unknown as StructureDefinition,
  [(sd39 as unknown as StructureDefinition).url]: sd39 as unknown as StructureDefinition,
  [(sd40 as unknown as StructureDefinition).url]: sd40 as unknown as StructureDefinition,
  [(sd41 as unknown as StructureDefinition).url]: sd41 as unknown as StructureDefinition,
  [(sd42 as unknown as StructureDefinition).url]: sd42 as unknown as StructureDefinition,
  [(sd43 as unknown as StructureDefinition).url]: sd43 as unknown as StructureDefinition,
  [(sd44 as unknown as StructureDefinition).url]: sd44 as unknown as StructureDefinition,
  [(sd45 as unknown as StructureDefinition).url]: sd45 as unknown as StructureDefinition,
  [(sd46 as unknown as StructureDefinition).url]: sd46 as unknown as StructureDefinition,
  [(sd47 as unknown as StructureDefinition).url]: sd47 as unknown as StructureDefinition,
  [(sd48 as unknown as StructureDefinition).url]: sd48 as unknown as StructureDefinition,
  [(sd49 as unknown as StructureDefinition).url]: sd49 as unknown as StructureDefinition,
  [(sd50 as unknown as StructureDefinition).url]: sd50 as unknown as StructureDefinition,
  [(sd51 as unknown as StructureDefinition).url]: sd51 as unknown as StructureDefinition,
  [(sd52 as unknown as StructureDefinition).url]: sd52 as unknown as StructureDefinition,
  [(sd53 as unknown as StructureDefinition).url]: sd53 as unknown as StructureDefinition,
  [(sd54 as unknown as StructureDefinition).url]: sd54 as unknown as StructureDefinition,
  [(sd55 as unknown as StructureDefinition).url]: sd55 as unknown as StructureDefinition,
  [(sd56 as unknown as StructureDefinition).url]: sd56 as unknown as StructureDefinition,
  [(sd57 as unknown as StructureDefinition).url]: sd57 as unknown as StructureDefinition,
  [(sd58 as unknown as StructureDefinition).url]: sd58 as unknown as StructureDefinition,
  [(sd59 as unknown as StructureDefinition).url]: sd59 as unknown as StructureDefinition,
  [(sd60 as unknown as StructureDefinition).url]: sd60 as unknown as StructureDefinition,
  [(sd61 as unknown as StructureDefinition).url]: sd61 as unknown as StructureDefinition,
  [(sd62 as unknown as StructureDefinition).url]: sd62 as unknown as StructureDefinition,
  [(sd63 as unknown as StructureDefinition).url]: sd63 as unknown as StructureDefinition,
  [(sd64 as unknown as StructureDefinition).url]: sd64 as unknown as StructureDefinition,
  [(sd65 as unknown as StructureDefinition).url]: sd65 as unknown as StructureDefinition,
  [(sd66 as unknown as StructureDefinition).url]: sd66 as unknown as StructureDefinition,
  [(sd67 as unknown as StructureDefinition).url]: sd67 as unknown as StructureDefinition,
  [(sd68 as unknown as StructureDefinition).url]: sd68 as unknown as StructureDefinition,
  [(sd69 as unknown as StructureDefinition).url]: sd69 as unknown as StructureDefinition,
  [(sd70 as unknown as StructureDefinition).url]: sd70 as unknown as StructureDefinition,
  [(sd71 as unknown as StructureDefinition).url]: sd71 as unknown as StructureDefinition,
  [(sd72 as unknown as StructureDefinition).url]: sd72 as unknown as StructureDefinition,
  [(sd73 as unknown as StructureDefinition).url]: sd73 as unknown as StructureDefinition,
  [(sd74 as unknown as StructureDefinition).url]: sd74 as unknown as StructureDefinition,
  [(sd75 as unknown as StructureDefinition).url]: sd75 as unknown as StructureDefinition,
  [(sd76 as unknown as StructureDefinition).url]: sd76 as unknown as StructureDefinition,
  [(sd77 as unknown as StructureDefinition).url]: sd77 as unknown as StructureDefinition,
  [(sd78 as unknown as StructureDefinition).url]: sd78 as unknown as StructureDefinition,
  [(sd79 as unknown as StructureDefinition).url]: sd79 as unknown as StructureDefinition,
  [(sd80 as unknown as StructureDefinition).url]: sd80 as unknown as StructureDefinition,
  [(sd81 as unknown as StructureDefinition).url]: sd81 as unknown as StructureDefinition,
  [(sd82 as unknown as StructureDefinition).url]: sd82 as unknown as StructureDefinition,
  [(sd83 as unknown as StructureDefinition).url]: sd83 as unknown as StructureDefinition,
  [(sd84 as unknown as StructureDefinition).url]: sd84 as unknown as StructureDefinition,
  [(sd85 as unknown as StructureDefinition).url]: sd85 as unknown as StructureDefinition,
  [(sd86 as unknown as StructureDefinition).url]: sd86 as unknown as StructureDefinition,
  [(sd87 as unknown as StructureDefinition).url]: sd87 as unknown as StructureDefinition,
  [(sd88 as unknown as StructureDefinition).url]: sd88 as unknown as StructureDefinition,
  [(sd89 as unknown as StructureDefinition).url]: sd89 as unknown as StructureDefinition,
  [(sd90 as unknown as StructureDefinition).url]: sd90 as unknown as StructureDefinition,
  [(sd91 as unknown as StructureDefinition).url]: sd91 as unknown as StructureDefinition,
  [(sd92 as unknown as StructureDefinition).url]: sd92 as unknown as StructureDefinition,
  [(sd93 as unknown as StructureDefinition).url]: sd93 as unknown as StructureDefinition,
  [(sd94 as unknown as StructureDefinition).url]: sd94 as unknown as StructureDefinition,
  [(sd95 as unknown as StructureDefinition).url]: sd95 as unknown as StructureDefinition,
  [(sd96 as unknown as StructureDefinition).url]: sd96 as unknown as StructureDefinition,
  [(sd97 as unknown as StructureDefinition).url]: sd97 as unknown as StructureDefinition,
  [(sd98 as unknown as StructureDefinition).url]: sd98 as unknown as StructureDefinition,
  [(sd99 as unknown as StructureDefinition).url]: sd99 as unknown as StructureDefinition,
  [(sd100 as unknown as StructureDefinition).url]: sd100 as unknown as StructureDefinition,
  [(sd101 as unknown as StructureDefinition).url]: sd101 as unknown as StructureDefinition,
  [(sd102 as unknown as StructureDefinition).url]: sd102 as unknown as StructureDefinition,
  [(sd103 as unknown as StructureDefinition).url]: sd103 as unknown as StructureDefinition,
  [(sd104 as unknown as StructureDefinition).url]: sd104 as unknown as StructureDefinition,
  [(sd105 as unknown as StructureDefinition).url]: sd105 as unknown as StructureDefinition,
  [(sd106 as unknown as StructureDefinition).url]: sd106 as unknown as StructureDefinition,
  [(sd107 as unknown as StructureDefinition).url]: sd107 as unknown as StructureDefinition,
  [(sd108 as unknown as StructureDefinition).url]: sd108 as unknown as StructureDefinition,
  [(sd109 as unknown as StructureDefinition).url]: sd109 as unknown as StructureDefinition,
  [(sd110 as unknown as StructureDefinition).url]: sd110 as unknown as StructureDefinition,
  [(sd111 as unknown as StructureDefinition).url]: sd111 as unknown as StructureDefinition,
  [(sd112 as unknown as StructureDefinition).url]: sd112 as unknown as StructureDefinition,
  [(sd113 as unknown as StructureDefinition).url]: sd113 as unknown as StructureDefinition,
  [(sd114 as unknown as StructureDefinition).url]: sd114 as unknown as StructureDefinition,
  [(sd115 as unknown as StructureDefinition).url]: sd115 as unknown as StructureDefinition,
  [(sd116 as unknown as StructureDefinition).url]: sd116 as unknown as StructureDefinition,
  [(sd117 as unknown as StructureDefinition).url]: sd117 as unknown as StructureDefinition,
  [(sd118 as unknown as StructureDefinition).url]: sd118 as unknown as StructureDefinition,
  [(sd119 as unknown as StructureDefinition).url]: sd119 as unknown as StructureDefinition,
  [(sd120 as unknown as StructureDefinition).url]: sd120 as unknown as StructureDefinition,
  [(sd121 as unknown as StructureDefinition).url]: sd121 as unknown as StructureDefinition,
  [(sd122 as unknown as StructureDefinition).url]: sd122 as unknown as StructureDefinition,
  [(sd123 as unknown as StructureDefinition).url]: sd123 as unknown as StructureDefinition,
  [(sd124 as unknown as StructureDefinition).url]: sd124 as unknown as StructureDefinition,
  [(sd125 as unknown as StructureDefinition).url]: sd125 as unknown as StructureDefinition,
  [(sd126 as unknown as StructureDefinition).url]: sd126 as unknown as StructureDefinition,
  [(sd127 as unknown as StructureDefinition).url]: sd127 as unknown as StructureDefinition,
  [(sd128 as unknown as StructureDefinition).url]: sd128 as unknown as StructureDefinition,
  [(sd129 as unknown as StructureDefinition).url]: sd129 as unknown as StructureDefinition,
  [(sd130 as unknown as StructureDefinition).url]: sd130 as unknown as StructureDefinition,
  [(sd131 as unknown as StructureDefinition).url]: sd131 as unknown as StructureDefinition,
  [(sd132 as unknown as StructureDefinition).url]: sd132 as unknown as StructureDefinition,
  [(sd133 as unknown as StructureDefinition).url]: sd133 as unknown as StructureDefinition,
  [(sd134 as unknown as StructureDefinition).url]: sd134 as unknown as StructureDefinition,
  [(sd135 as unknown as StructureDefinition).url]: sd135 as unknown as StructureDefinition,
  [(sd136 as unknown as StructureDefinition).url]: sd136 as unknown as StructureDefinition,
  [(sd137 as unknown as StructureDefinition).url]: sd137 as unknown as StructureDefinition,
  [(sd138 as unknown as StructureDefinition).url]: sd138 as unknown as StructureDefinition,
  [(sd139 as unknown as StructureDefinition).url]: sd139 as unknown as StructureDefinition,
  [(sd140 as unknown as StructureDefinition).url]: sd140 as unknown as StructureDefinition,
  [(sd141 as unknown as StructureDefinition).url]: sd141 as unknown as StructureDefinition,
  [(sd142 as unknown as StructureDefinition).url]: sd142 as unknown as StructureDefinition,
  [(sd143 as unknown as StructureDefinition).url]: sd143 as unknown as StructureDefinition,
  [(sd144 as unknown as StructureDefinition).url]: sd144 as unknown as StructureDefinition,
  [(sd145 as unknown as StructureDefinition).url]: sd145 as unknown as StructureDefinition,
  [(sd146 as unknown as StructureDefinition).url]: sd146 as unknown as StructureDefinition,
  [(sd147 as unknown as StructureDefinition).url]: sd147 as unknown as StructureDefinition,
  [(sd148 as unknown as StructureDefinition).url]: sd148 as unknown as StructureDefinition,
  [(sd149 as unknown as StructureDefinition).url]: sd149 as unknown as StructureDefinition,
  [(sd150 as unknown as StructureDefinition).url]: sd150 as unknown as StructureDefinition,
  [(sd151 as unknown as StructureDefinition).url]: sd151 as unknown as StructureDefinition,
  [(sd152 as unknown as StructureDefinition).url]: sd152 as unknown as StructureDefinition,
  [(sd153 as unknown as StructureDefinition).url]: sd153 as unknown as StructureDefinition,
  [(sd154 as unknown as StructureDefinition).url]: sd154 as unknown as StructureDefinition,
  [(sd155 as unknown as StructureDefinition).url]: sd155 as unknown as StructureDefinition,
  [(sd156 as unknown as StructureDefinition).url]: sd156 as unknown as StructureDefinition,
  [(sd157 as unknown as StructureDefinition).url]: sd157 as unknown as StructureDefinition,
  [(sd158 as unknown as StructureDefinition).url]: sd158 as unknown as StructureDefinition,
  [(sd159 as unknown as StructureDefinition).url]: sd159 as unknown as StructureDefinition,
  [(sd160 as unknown as StructureDefinition).url]: sd160 as unknown as StructureDefinition,
  [(sd161 as unknown as StructureDefinition).url]: sd161 as unknown as StructureDefinition,
  [(sd162 as unknown as StructureDefinition).url]: sd162 as unknown as StructureDefinition,
  [(sd163 as unknown as StructureDefinition).url]: sd163 as unknown as StructureDefinition,
  [(sd164 as unknown as StructureDefinition).url]: sd164 as unknown as StructureDefinition,
  [(sd165 as unknown as StructureDefinition).url]: sd165 as unknown as StructureDefinition,
  [(sd166 as unknown as StructureDefinition).url]: sd166 as unknown as StructureDefinition,
  [(sd167 as unknown as StructureDefinition).url]: sd167 as unknown as StructureDefinition,
  [(sd168 as unknown as StructureDefinition).url]: sd168 as unknown as StructureDefinition,
  [(sd169 as unknown as StructureDefinition).url]: sd169 as unknown as StructureDefinition,
  [(sd170 as unknown as StructureDefinition).url]: sd170 as unknown as StructureDefinition,
  [(sd171 as unknown as StructureDefinition).url]: sd171 as unknown as StructureDefinition,
  [(sd172 as unknown as StructureDefinition).url]: sd172 as unknown as StructureDefinition,
  [(sd173 as unknown as StructureDefinition).url]: sd173 as unknown as StructureDefinition,
  [(sd174 as unknown as StructureDefinition).url]: sd174 as unknown as StructureDefinition,
  [(sd175 as unknown as StructureDefinition).url]: sd175 as unknown as StructureDefinition,
  [(sd176 as unknown as StructureDefinition).url]: sd176 as unknown as StructureDefinition,
  [(sd177 as unknown as StructureDefinition).url]: sd177 as unknown as StructureDefinition,
  [(sd178 as unknown as StructureDefinition).url]: sd178 as unknown as StructureDefinition,
  [(sd179 as unknown as StructureDefinition).url]: sd179 as unknown as StructureDefinition,
  [(sd180 as unknown as StructureDefinition).url]: sd180 as unknown as StructureDefinition,
  [(sd181 as unknown as StructureDefinition).url]: sd181 as unknown as StructureDefinition,
  [(sd182 as unknown as StructureDefinition).url]: sd182 as unknown as StructureDefinition,
  [(sd183 as unknown as StructureDefinition).url]: sd183 as unknown as StructureDefinition,
  [(sd184 as unknown as StructureDefinition).url]: sd184 as unknown as StructureDefinition,
  [(sd185 as unknown as StructureDefinition).url]: sd185 as unknown as StructureDefinition,
  [(sd186 as unknown as StructureDefinition).url]: sd186 as unknown as StructureDefinition,
  [(sd187 as unknown as StructureDefinition).url]: sd187 as unknown as StructureDefinition,
  [(sd188 as unknown as StructureDefinition).url]: sd188 as unknown as StructureDefinition,
  [(sd189 as unknown as StructureDefinition).url]: sd189 as unknown as StructureDefinition,
  [(sd190 as unknown as StructureDefinition).url]: sd190 as unknown as StructureDefinition,
  [(sd191 as unknown as StructureDefinition).url]: sd191 as unknown as StructureDefinition,
  [(sd192 as unknown as StructureDefinition).url]: sd192 as unknown as StructureDefinition,
  [(sd193 as unknown as StructureDefinition).url]: sd193 as unknown as StructureDefinition,
  [(sd194 as unknown as StructureDefinition).url]: sd194 as unknown as StructureDefinition,
  [(sd195 as unknown as StructureDefinition).url]: sd195 as unknown as StructureDefinition,
  [(sd196 as unknown as StructureDefinition).url]: sd196 as unknown as StructureDefinition,
  [(sd197 as unknown as StructureDefinition).url]: sd197 as unknown as StructureDefinition,
  [(sd198 as unknown as StructureDefinition).url]: sd198 as unknown as StructureDefinition,
  [(sd199 as unknown as StructureDefinition).url]: sd199 as unknown as StructureDefinition,
  [(sd200 as unknown as StructureDefinition).url]: sd200 as unknown as StructureDefinition,
  [(sd201 as unknown as StructureDefinition).url]: sd201 as unknown as StructureDefinition,
  [(sd202 as unknown as StructureDefinition).url]: sd202 as unknown as StructureDefinition,
  [(sd203 as unknown as StructureDefinition).url]: sd203 as unknown as StructureDefinition,
  [(sd204 as unknown as StructureDefinition).url]: sd204 as unknown as StructureDefinition,
  [(sd205 as unknown as StructureDefinition).url]: sd205 as unknown as StructureDefinition,
  [(sd206 as unknown as StructureDefinition).url]: sd206 as unknown as StructureDefinition,
  [(sd207 as unknown as StructureDefinition).url]: sd207 as unknown as StructureDefinition,
  [(sd208 as unknown as StructureDefinition).url]: sd208 as unknown as StructureDefinition,
  [(sd209 as unknown as StructureDefinition).url]: sd209 as unknown as StructureDefinition,
  [(sd210 as unknown as StructureDefinition).url]: sd210 as unknown as StructureDefinition,
  [(sd211 as unknown as StructureDefinition).url]: sd211 as unknown as StructureDefinition,
  [(sd212 as unknown as StructureDefinition).url]: sd212 as unknown as StructureDefinition,
  [(sd213 as unknown as StructureDefinition).url]: sd213 as unknown as StructureDefinition,
  [(sd214 as unknown as StructureDefinition).url]: sd214 as unknown as StructureDefinition,
  [(sd215 as unknown as StructureDefinition).url]: sd215 as unknown as StructureDefinition,
  [(sd216 as unknown as StructureDefinition).url]: sd216 as unknown as StructureDefinition,
  [(sd217 as unknown as StructureDefinition).url]: sd217 as unknown as StructureDefinition,
  [(sd218 as unknown as StructureDefinition).url]: sd218 as unknown as StructureDefinition,
  [(sd219 as unknown as StructureDefinition).url]: sd219 as unknown as StructureDefinition,
  [(sd220 as unknown as StructureDefinition).url]: sd220 as unknown as StructureDefinition,
  [(sd221 as unknown as StructureDefinition).url]: sd221 as unknown as StructureDefinition,
  [(sd222 as unknown as StructureDefinition).url]: sd222 as unknown as StructureDefinition,
  [(sd223 as unknown as StructureDefinition).url]: sd223 as unknown as StructureDefinition,
  [(sd224 as unknown as StructureDefinition).url]: sd224 as unknown as StructureDefinition,
  [(sd225 as unknown as StructureDefinition).url]: sd225 as unknown as StructureDefinition,
  [(sd226 as unknown as StructureDefinition).url]: sd226 as unknown as StructureDefinition,
  [(sd227 as unknown as StructureDefinition).url]: sd227 as unknown as StructureDefinition,
  [(sd228 as unknown as StructureDefinition).url]: sd228 as unknown as StructureDefinition,
  [(sd229 as unknown as StructureDefinition).url]: sd229 as unknown as StructureDefinition,
  [(sd230 as unknown as StructureDefinition).url]: sd230 as unknown as StructureDefinition,
  [(sd231 as unknown as StructureDefinition).url]: sd231 as unknown as StructureDefinition,
  [(sd232 as unknown as StructureDefinition).url]: sd232 as unknown as StructureDefinition,
  [(sd233 as unknown as StructureDefinition).url]: sd233 as unknown as StructureDefinition,
  [(sd234 as unknown as StructureDefinition).url]: sd234 as unknown as StructureDefinition,
  [(sd235 as unknown as StructureDefinition).url]: sd235 as unknown as StructureDefinition,
  [(sd236 as unknown as StructureDefinition).url]: sd236 as unknown as StructureDefinition,
  [(sd237 as unknown as StructureDefinition).url]: sd237 as unknown as StructureDefinition,
  [(sd238 as unknown as StructureDefinition).url]: sd238 as unknown as StructureDefinition,
  [(sd239 as unknown as StructureDefinition).url]: sd239 as unknown as StructureDefinition,
  [(sd240 as unknown as StructureDefinition).url]: sd240 as unknown as StructureDefinition,
  [(sd241 as unknown as StructureDefinition).url]: sd241 as unknown as StructureDefinition,
  [(sd242 as unknown as StructureDefinition).url]: sd242 as unknown as StructureDefinition,
  [(sd243 as unknown as StructureDefinition).url]: sd243 as unknown as StructureDefinition,
  [(sd244 as unknown as StructureDefinition).url]: sd244 as unknown as StructureDefinition,
  [(sd245 as unknown as StructureDefinition).url]: sd245 as unknown as StructureDefinition,
  [(sd246 as unknown as StructureDefinition).url]: sd246 as unknown as StructureDefinition,
  [(sd247 as unknown as StructureDefinition).url]: sd247 as unknown as StructureDefinition,
  [(sd248 as unknown as StructureDefinition).url]: sd248 as unknown as StructureDefinition,
  [(sd249 as unknown as StructureDefinition).url]: sd249 as unknown as StructureDefinition,
  [(sd250 as unknown as StructureDefinition).url]: sd250 as unknown as StructureDefinition,
  [(sd251 as unknown as StructureDefinition).url]: sd251 as unknown as StructureDefinition,
  [(sd252 as unknown as StructureDefinition).url]: sd252 as unknown as StructureDefinition,
  [(sd253 as unknown as StructureDefinition).url]: sd253 as unknown as StructureDefinition,
  [(sd254 as unknown as StructureDefinition).url]: sd254 as unknown as StructureDefinition,
  [(sd255 as unknown as StructureDefinition).url]: sd255 as unknown as StructureDefinition,
  [(sd256 as unknown as StructureDefinition).url]: sd256 as unknown as StructureDefinition,
  [(sd257 as unknown as StructureDefinition).url]: sd257 as unknown as StructureDefinition,
  [(sd258 as unknown as StructureDefinition).url]: sd258 as unknown as StructureDefinition,
  [(sd259 as unknown as StructureDefinition).url]: sd259 as unknown as StructureDefinition,
  [(sd260 as unknown as StructureDefinition).url]: sd260 as unknown as StructureDefinition,
  [(sd261 as unknown as StructureDefinition).url]: sd261 as unknown as StructureDefinition,
  [(sd262 as unknown as StructureDefinition).url]: sd262 as unknown as StructureDefinition,
  [(sd263 as unknown as StructureDefinition).url]: sd263 as unknown as StructureDefinition,
  [(sd264 as unknown as StructureDefinition).url]: sd264 as unknown as StructureDefinition,
  [(sd265 as unknown as StructureDefinition).url]: sd265 as unknown as StructureDefinition,
  [(sd266 as unknown as StructureDefinition).url]: sd266 as unknown as StructureDefinition,
  [(sd267 as unknown as StructureDefinition).url]: sd267 as unknown as StructureDefinition,
  [(sd268 as unknown as StructureDefinition).url]: sd268 as unknown as StructureDefinition,
  [(sd269 as unknown as StructureDefinition).url]: sd269 as unknown as StructureDefinition,
  [(sd270 as unknown as StructureDefinition).url]: sd270 as unknown as StructureDefinition,
  [(sd271 as unknown as StructureDefinition).url]: sd271 as unknown as StructureDefinition,
  [(sd272 as unknown as StructureDefinition).url]: sd272 as unknown as StructureDefinition,
  [(sd273 as unknown as StructureDefinition).url]: sd273 as unknown as StructureDefinition,
  [(sd274 as unknown as StructureDefinition).url]: sd274 as unknown as StructureDefinition,
  [(sd275 as unknown as StructureDefinition).url]: sd275 as unknown as StructureDefinition,
  [(sd276 as unknown as StructureDefinition).url]: sd276 as unknown as StructureDefinition,
  [(sd277 as unknown as StructureDefinition).url]: sd277 as unknown as StructureDefinition,
  [(sd278 as unknown as StructureDefinition).url]: sd278 as unknown as StructureDefinition,
  [(sd279 as unknown as StructureDefinition).url]: sd279 as unknown as StructureDefinition,
  [(sd280 as unknown as StructureDefinition).url]: sd280 as unknown as StructureDefinition,
  [(sd281 as unknown as StructureDefinition).url]: sd281 as unknown as StructureDefinition,
  [(sd282 as unknown as StructureDefinition).url]: sd282 as unknown as StructureDefinition,
  [(sd283 as unknown as StructureDefinition).url]: sd283 as unknown as StructureDefinition,
  [(sd284 as unknown as StructureDefinition).url]: sd284 as unknown as StructureDefinition,
  [(sd285 as unknown as StructureDefinition).url]: sd285 as unknown as StructureDefinition,
  [(sd286 as unknown as StructureDefinition).url]: sd286 as unknown as StructureDefinition,
  [(sd287 as unknown as StructureDefinition).url]: sd287 as unknown as StructureDefinition,
  [(sd288 as unknown as StructureDefinition).url]: sd288 as unknown as StructureDefinition,
  [(sd289 as unknown as StructureDefinition).url]: sd289 as unknown as StructureDefinition,
  [(sd290 as unknown as StructureDefinition).url]: sd290 as unknown as StructureDefinition,
  [(sd291 as unknown as StructureDefinition).url]: sd291 as unknown as StructureDefinition,
  [(sd292 as unknown as StructureDefinition).url]: sd292 as unknown as StructureDefinition,
  [(sd293 as unknown as StructureDefinition).url]: sd293 as unknown as StructureDefinition,
  [(sd294 as unknown as StructureDefinition).url]: sd294 as unknown as StructureDefinition,
  [(sd295 as unknown as StructureDefinition).url]: sd295 as unknown as StructureDefinition,
  [(sd296 as unknown as StructureDefinition).url]: sd296 as unknown as StructureDefinition,
  [(sd297 as unknown as StructureDefinition).url]: sd297 as unknown as StructureDefinition,
  [(sd298 as unknown as StructureDefinition).url]: sd298 as unknown as StructureDefinition,
  [(sd299 as unknown as StructureDefinition).url]: sd299 as unknown as StructureDefinition,
  [(sd300 as unknown as StructureDefinition).url]: sd300 as unknown as StructureDefinition,
  [(sd301 as unknown as StructureDefinition).url]: sd301 as unknown as StructureDefinition,
  [(sd302 as unknown as StructureDefinition).url]: sd302 as unknown as StructureDefinition,
  [(sd303 as unknown as StructureDefinition).url]: sd303 as unknown as StructureDefinition,
  [(sd304 as unknown as StructureDefinition).url]: sd304 as unknown as StructureDefinition,
  [(sd305 as unknown as StructureDefinition).url]: sd305 as unknown as StructureDefinition,
  [(sd306 as unknown as StructureDefinition).url]: sd306 as unknown as StructureDefinition,
  [(sd307 as unknown as StructureDefinition).url]: sd307 as unknown as StructureDefinition,
  [(sd308 as unknown as StructureDefinition).url]: sd308 as unknown as StructureDefinition,
  [(sd309 as unknown as StructureDefinition).url]: sd309 as unknown as StructureDefinition,
  [(sd310 as unknown as StructureDefinition).url]: sd310 as unknown as StructureDefinition,
  [(sd311 as unknown as StructureDefinition).url]: sd311 as unknown as StructureDefinition,
  [(sd312 as unknown as StructureDefinition).url]: sd312 as unknown as StructureDefinition,
  [(sd313 as unknown as StructureDefinition).url]: sd313 as unknown as StructureDefinition,
  [(sd314 as unknown as StructureDefinition).url]: sd314 as unknown as StructureDefinition,
  [(sd315 as unknown as StructureDefinition).url]: sd315 as unknown as StructureDefinition,
  [(sd316 as unknown as StructureDefinition).url]: sd316 as unknown as StructureDefinition,
  [(sd317 as unknown as StructureDefinition).url]: sd317 as unknown as StructureDefinition,
  [(sd318 as unknown as StructureDefinition).url]: sd318 as unknown as StructureDefinition,
  [(sd319 as unknown as StructureDefinition).url]: sd319 as unknown as StructureDefinition,
  [(sd320 as unknown as StructureDefinition).url]: sd320 as unknown as StructureDefinition,
  [(sd321 as unknown as StructureDefinition).url]: sd321 as unknown as StructureDefinition,
  [(sd322 as unknown as StructureDefinition).url]: sd322 as unknown as StructureDefinition,
  [(sd323 as unknown as StructureDefinition).url]: sd323 as unknown as StructureDefinition,
  [(sd324 as unknown as StructureDefinition).url]: sd324 as unknown as StructureDefinition,
  [(sd325 as unknown as StructureDefinition).url]: sd325 as unknown as StructureDefinition,
  [(sd326 as unknown as StructureDefinition).url]: sd326 as unknown as StructureDefinition,
  [(sd327 as unknown as StructureDefinition).url]: sd327 as unknown as StructureDefinition,
  [(sd328 as unknown as StructureDefinition).url]: sd328 as unknown as StructureDefinition,
  [(sd329 as unknown as StructureDefinition).url]: sd329 as unknown as StructureDefinition,
  [(sd330 as unknown as StructureDefinition).url]: sd330 as unknown as StructureDefinition,
  [(sd331 as unknown as StructureDefinition).url]: sd331 as unknown as StructureDefinition,
  [(sd332 as unknown as StructureDefinition).url]: sd332 as unknown as StructureDefinition,
  [(sd333 as unknown as StructureDefinition).url]: sd333 as unknown as StructureDefinition,
  [(sd334 as unknown as StructureDefinition).url]: sd334 as unknown as StructureDefinition,
  [(sd335 as unknown as StructureDefinition).url]: sd335 as unknown as StructureDefinition,
  [(sd336 as unknown as StructureDefinition).url]: sd336 as unknown as StructureDefinition,
  [(sd337 as unknown as StructureDefinition).url]: sd337 as unknown as StructureDefinition,
  [(sd338 as unknown as StructureDefinition).url]: sd338 as unknown as StructureDefinition,
  [(sd339 as unknown as StructureDefinition).url]: sd339 as unknown as StructureDefinition,
  [(sd340 as unknown as StructureDefinition).url]: sd340 as unknown as StructureDefinition,
  [(sd341 as unknown as StructureDefinition).url]: sd341 as unknown as StructureDefinition,
  [(sd342 as unknown as StructureDefinition).url]: sd342 as unknown as StructureDefinition,
  [(sd343 as unknown as StructureDefinition).url]: sd343 as unknown as StructureDefinition,
  [(sd344 as unknown as StructureDefinition).url]: sd344 as unknown as StructureDefinition,
  [(sd345 as unknown as StructureDefinition).url]: sd345 as unknown as StructureDefinition,
  [(sd346 as unknown as StructureDefinition).url]: sd346 as unknown as StructureDefinition,
  [(sd347 as unknown as StructureDefinition).url]: sd347 as unknown as StructureDefinition,
  [(sd348 as unknown as StructureDefinition).url]: sd348 as unknown as StructureDefinition,
  [(sd349 as unknown as StructureDefinition).url]: sd349 as unknown as StructureDefinition,
  [(sd350 as unknown as StructureDefinition).url]: sd350 as unknown as StructureDefinition,
  [(sd351 as unknown as StructureDefinition).url]: sd351 as unknown as StructureDefinition,
  [(sd352 as unknown as StructureDefinition).url]: sd352 as unknown as StructureDefinition,
  [(sd353 as unknown as StructureDefinition).url]: sd353 as unknown as StructureDefinition,
  [(sd354 as unknown as StructureDefinition).url]: sd354 as unknown as StructureDefinition,
  [(sd355 as unknown as StructureDefinition).url]: sd355 as unknown as StructureDefinition,
  [(sd356 as unknown as StructureDefinition).url]: sd356 as unknown as StructureDefinition,
  [(sd357 as unknown as StructureDefinition).url]: sd357 as unknown as StructureDefinition,
  [(sd358 as unknown as StructureDefinition).url]: sd358 as unknown as StructureDefinition,
  [(sd359 as unknown as StructureDefinition).url]: sd359 as unknown as StructureDefinition,
  [(sd360 as unknown as StructureDefinition).url]: sd360 as unknown as StructureDefinition,
  [(sd361 as unknown as StructureDefinition).url]: sd361 as unknown as StructureDefinition,
  [(sd362 as unknown as StructureDefinition).url]: sd362 as unknown as StructureDefinition,
  [(sd363 as unknown as StructureDefinition).url]: sd363 as unknown as StructureDefinition,
  [(sd364 as unknown as StructureDefinition).url]: sd364 as unknown as StructureDefinition,
  [(sd365 as unknown as StructureDefinition).url]: sd365 as unknown as StructureDefinition,
  [(sd366 as unknown as StructureDefinition).url]: sd366 as unknown as StructureDefinition,
  [(sd367 as unknown as StructureDefinition).url]: sd367 as unknown as StructureDefinition,
  [(sd368 as unknown as StructureDefinition).url]: sd368 as unknown as StructureDefinition,
  [(sd369 as unknown as StructureDefinition).url]: sd369 as unknown as StructureDefinition,
  [(sd370 as unknown as StructureDefinition).url]: sd370 as unknown as StructureDefinition,
  [(sd371 as unknown as StructureDefinition).url]: sd371 as unknown as StructureDefinition,
  [(sd372 as unknown as StructureDefinition).url]: sd372 as unknown as StructureDefinition,
  [(sd373 as unknown as StructureDefinition).url]: sd373 as unknown as StructureDefinition,
  [(sd374 as unknown as StructureDefinition).url]: sd374 as unknown as StructureDefinition,
  [(sd375 as unknown as StructureDefinition).url]: sd375 as unknown as StructureDefinition,
  [(sd376 as unknown as StructureDefinition).url]: sd376 as unknown as StructureDefinition,
  [(sd377 as unknown as StructureDefinition).url]: sd377 as unknown as StructureDefinition,
  [(sd378 as unknown as StructureDefinition).url]: sd378 as unknown as StructureDefinition,
  [(sd379 as unknown as StructureDefinition).url]: sd379 as unknown as StructureDefinition,
  [(sd380 as unknown as StructureDefinition).url]: sd380 as unknown as StructureDefinition,
  [(sd381 as unknown as StructureDefinition).url]: sd381 as unknown as StructureDefinition,
  [(sd382 as unknown as StructureDefinition).url]: sd382 as unknown as StructureDefinition,
  [(sd383 as unknown as StructureDefinition).url]: sd383 as unknown as StructureDefinition,
  [(sd384 as unknown as StructureDefinition).url]: sd384 as unknown as StructureDefinition,
  [(sd385 as unknown as StructureDefinition).url]: sd385 as unknown as StructureDefinition,
  [(sd386 as unknown as StructureDefinition).url]: sd386 as unknown as StructureDefinition,
  [(sd387 as unknown as StructureDefinition).url]: sd387 as unknown as StructureDefinition,
  [(sd388 as unknown as StructureDefinition).url]: sd388 as unknown as StructureDefinition,
  [(sd389 as unknown as StructureDefinition).url]: sd389 as unknown as StructureDefinition,
  [(sd390 as unknown as StructureDefinition).url]: sd390 as unknown as StructureDefinition,
  [(sd391 as unknown as StructureDefinition).url]: sd391 as unknown as StructureDefinition,
  [(sd392 as unknown as StructureDefinition).url]: sd392 as unknown as StructureDefinition,
  [(sd393 as unknown as StructureDefinition).url]: sd393 as unknown as StructureDefinition,
  [(sd394 as unknown as StructureDefinition).url]: sd394 as unknown as StructureDefinition,
  [(sd395 as unknown as StructureDefinition).url]: sd395 as unknown as StructureDefinition,
  [(sd396 as unknown as StructureDefinition).url]: sd396 as unknown as StructureDefinition,
  [(sd397 as unknown as StructureDefinition).url]: sd397 as unknown as StructureDefinition,
  [(sd398 as unknown as StructureDefinition).url]: sd398 as unknown as StructureDefinition,
  [(sd399 as unknown as StructureDefinition).url]: sd399 as unknown as StructureDefinition,
  [(sd400 as unknown as StructureDefinition).url]: sd400 as unknown as StructureDefinition,
  [(sd401 as unknown as StructureDefinition).url]: sd401 as unknown as StructureDefinition,
  [(sd402 as unknown as StructureDefinition).url]: sd402 as unknown as StructureDefinition,
  [(sd403 as unknown as StructureDefinition).url]: sd403 as unknown as StructureDefinition,
  [(sd404 as unknown as StructureDefinition).url]: sd404 as unknown as StructureDefinition,
  [(sd405 as unknown as StructureDefinition).url]: sd405 as unknown as StructureDefinition,
  [(sd406 as unknown as StructureDefinition).url]: sd406 as unknown as StructureDefinition,
  [(sd407 as unknown as StructureDefinition).url]: sd407 as unknown as StructureDefinition,
  [(sd408 as unknown as StructureDefinition).url]: sd408 as unknown as StructureDefinition,
  [(sd409 as unknown as StructureDefinition).url]: sd409 as unknown as StructureDefinition,
  [(sd410 as unknown as StructureDefinition).url]: sd410 as unknown as StructureDefinition,
  [(sd411 as unknown as StructureDefinition).url]: sd411 as unknown as StructureDefinition,
  [(sd412 as unknown as StructureDefinition).url]: sd412 as unknown as StructureDefinition,
  [(sd413 as unknown as StructureDefinition).url]: sd413 as unknown as StructureDefinition,
  [(sd414 as unknown as StructureDefinition).url]: sd414 as unknown as StructureDefinition,
  [(sd415 as unknown as StructureDefinition).url]: sd415 as unknown as StructureDefinition,
  [(sd416 as unknown as StructureDefinition).url]: sd416 as unknown as StructureDefinition,
  [(sd417 as unknown as StructureDefinition).url]: sd417 as unknown as StructureDefinition,
  [(sd418 as unknown as StructureDefinition).url]: sd418 as unknown as StructureDefinition,
  [(sd419 as unknown as StructureDefinition).url]: sd419 as unknown as StructureDefinition,
  [(sd420 as unknown as StructureDefinition).url]: sd420 as unknown as StructureDefinition,
  [(sd421 as unknown as StructureDefinition).url]: sd421 as unknown as StructureDefinition,
  [(sd422 as unknown as StructureDefinition).url]: sd422 as unknown as StructureDefinition,
  [(sd423 as unknown as StructureDefinition).url]: sd423 as unknown as StructureDefinition,
  [(sd424 as unknown as StructureDefinition).url]: sd424 as unknown as StructureDefinition,
  [(sd425 as unknown as StructureDefinition).url]: sd425 as unknown as StructureDefinition,
  [(sd426 as unknown as StructureDefinition).url]: sd426 as unknown as StructureDefinition,
  [(sd427 as unknown as StructureDefinition).url]: sd427 as unknown as StructureDefinition,
  [(sd428 as unknown as StructureDefinition).url]: sd428 as unknown as StructureDefinition,
  [(sd429 as unknown as StructureDefinition).url]: sd429 as unknown as StructureDefinition,
  [(sd430 as unknown as StructureDefinition).url]: sd430 as unknown as StructureDefinition,
  [(sd431 as unknown as StructureDefinition).url]: sd431 as unknown as StructureDefinition,
  [(sd432 as unknown as StructureDefinition).url]: sd432 as unknown as StructureDefinition,
  [(sd433 as unknown as StructureDefinition).url]: sd433 as unknown as StructureDefinition,
  [(sd434 as unknown as StructureDefinition).url]: sd434 as unknown as StructureDefinition,
  [(sd435 as unknown as StructureDefinition).url]: sd435 as unknown as StructureDefinition,
  [(sd436 as unknown as StructureDefinition).url]: sd436 as unknown as StructureDefinition,
  [(sd437 as unknown as StructureDefinition).url]: sd437 as unknown as StructureDefinition,
  [(sd438 as unknown as StructureDefinition).url]: sd438 as unknown as StructureDefinition,
  [(sd439 as unknown as StructureDefinition).url]: sd439 as unknown as StructureDefinition,
  [(sd440 as unknown as StructureDefinition).url]: sd440 as unknown as StructureDefinition,
  [(sd441 as unknown as StructureDefinition).url]: sd441 as unknown as StructureDefinition,
  [(sd442 as unknown as StructureDefinition).url]: sd442 as unknown as StructureDefinition,
  [(sd443 as unknown as StructureDefinition).url]: sd443 as unknown as StructureDefinition,
  [(sd444 as unknown as StructureDefinition).url]: sd444 as unknown as StructureDefinition,
  [(sd445 as unknown as StructureDefinition).url]: sd445 as unknown as StructureDefinition,
  [(sd446 as unknown as StructureDefinition).url]: sd446 as unknown as StructureDefinition,
  [(sd447 as unknown as StructureDefinition).url]: sd447 as unknown as StructureDefinition,
  [(sd448 as unknown as StructureDefinition).url]: sd448 as unknown as StructureDefinition,
  [(sd449 as unknown as StructureDefinition).url]: sd449 as unknown as StructureDefinition,
  [(sd450 as unknown as StructureDefinition).url]: sd450 as unknown as StructureDefinition,
  [(sd451 as unknown as StructureDefinition).url]: sd451 as unknown as StructureDefinition,
  [(sd452 as unknown as StructureDefinition).url]: sd452 as unknown as StructureDefinition,
  [(sd453 as unknown as StructureDefinition).url]: sd453 as unknown as StructureDefinition,
  [(sd454 as unknown as StructureDefinition).url]: sd454 as unknown as StructureDefinition,
  [(sd455 as unknown as StructureDefinition).url]: sd455 as unknown as StructureDefinition,
  [(sd456 as unknown as StructureDefinition).url]: sd456 as unknown as StructureDefinition,
  [(sd457 as unknown as StructureDefinition).url]: sd457 as unknown as StructureDefinition,
  [(sd458 as unknown as StructureDefinition).url]: sd458 as unknown as StructureDefinition,
  [(sd459 as unknown as StructureDefinition).url]: sd459 as unknown as StructureDefinition,
  [(sd460 as unknown as StructureDefinition).url]: sd460 as unknown as StructureDefinition,
  [(sd461 as unknown as StructureDefinition).url]: sd461 as unknown as StructureDefinition,
  [(sd462 as unknown as StructureDefinition).url]: sd462 as unknown as StructureDefinition,
  [(sd463 as unknown as StructureDefinition).url]: sd463 as unknown as StructureDefinition,
  [(sd464 as unknown as StructureDefinition).url]: sd464 as unknown as StructureDefinition,
  [(sd465 as unknown as StructureDefinition).url]: sd465 as unknown as StructureDefinition,
  [(sd466 as unknown as StructureDefinition).url]: sd466 as unknown as StructureDefinition,
  [(sd467 as unknown as StructureDefinition).url]: sd467 as unknown as StructureDefinition,
  [(sd468 as unknown as StructureDefinition).url]: sd468 as unknown as StructureDefinition,
  [(sd469 as unknown as StructureDefinition).url]: sd469 as unknown as StructureDefinition,
  [(sd470 as unknown as StructureDefinition).url]: sd470 as unknown as StructureDefinition,
  [(sd471 as unknown as StructureDefinition).url]: sd471 as unknown as StructureDefinition,
  [(sd472 as unknown as StructureDefinition).url]: sd472 as unknown as StructureDefinition,
  [(sd473 as unknown as StructureDefinition).url]: sd473 as unknown as StructureDefinition,
  [(sd474 as unknown as StructureDefinition).url]: sd474 as unknown as StructureDefinition,
  [(sd475 as unknown as StructureDefinition).url]: sd475 as unknown as StructureDefinition,
  [(sd476 as unknown as StructureDefinition).url]: sd476 as unknown as StructureDefinition,
  [(sd477 as unknown as StructureDefinition).url]: sd477 as unknown as StructureDefinition,
  [(sd478 as unknown as StructureDefinition).url]: sd478 as unknown as StructureDefinition,
  [(sd479 as unknown as StructureDefinition).url]: sd479 as unknown as StructureDefinition,
  [(sd480 as unknown as StructureDefinition).url]: sd480 as unknown as StructureDefinition,
  [(sd481 as unknown as StructureDefinition).url]: sd481 as unknown as StructureDefinition,
  [(sd482 as unknown as StructureDefinition).url]: sd482 as unknown as StructureDefinition,
  [(sd483 as unknown as StructureDefinition).url]: sd483 as unknown as StructureDefinition,
  [(sd484 as unknown as StructureDefinition).url]: sd484 as unknown as StructureDefinition,
  [(sd485 as unknown as StructureDefinition).url]: sd485 as unknown as StructureDefinition,
  [(sd486 as unknown as StructureDefinition).url]: sd486 as unknown as StructureDefinition,
  [(sd487 as unknown as StructureDefinition).url]: sd487 as unknown as StructureDefinition,
  [(sd488 as unknown as StructureDefinition).url]: sd488 as unknown as StructureDefinition,
  [(sd489 as unknown as StructureDefinition).url]: sd489 as unknown as StructureDefinition,
  [(sd490 as unknown as StructureDefinition).url]: sd490 as unknown as StructureDefinition,
  [(sd491 as unknown as StructureDefinition).url]: sd491 as unknown as StructureDefinition,
  [(sd492 as unknown as StructureDefinition).url]: sd492 as unknown as StructureDefinition,
  [(sd493 as unknown as StructureDefinition).url]: sd493 as unknown as StructureDefinition,
  [(sd494 as unknown as StructureDefinition).url]: sd494 as unknown as StructureDefinition,
  [(sd495 as unknown as StructureDefinition).url]: sd495 as unknown as StructureDefinition,
  [(sd496 as unknown as StructureDefinition).url]: sd496 as unknown as StructureDefinition,
  [(sd497 as unknown as StructureDefinition).url]: sd497 as unknown as StructureDefinition,
  [(sd498 as unknown as StructureDefinition).url]: sd498 as unknown as StructureDefinition,
  [(sd499 as unknown as StructureDefinition).url]: sd499 as unknown as StructureDefinition,
  [(sd500 as unknown as StructureDefinition).url]: sd500 as unknown as StructureDefinition,
};
