/**
 * Bundled MII StructureDefinition registry for Phase 05 completeness checks.
 *
 * Profiles are trimmed to the fields the completeness walker reads
 * (`url`, `name`, `type`, `snapshot.element[]` with `path`, `min`,
 * `mustSupport`). The full MII 2025 snapshots are NOT bundled — see
 * Pitfall 7 in 05-RESEARCH.md for the bundle-size rationale.
 *
 * Source: derived from the MII Kerndatensatz 2025 packages on Simplifier.
 * Assumption A1 (redistributability) is the author's responsibility.
 *
 * To update:
 * 1. Fetch the canonical StructureDefinition from Simplifier.
 * 2. Trim to `{ resourceType, url, name, type, snapshot: { element: [
 *    { path, min?, max?, mustSupport?, sliceName? } ... ] } }`.
 * 3. Replace the file under src/quality/profiles/.
 * 4. Leave the registry mapping below untouched unless adding a new type
 *    (also update BUNDLED_PROFILE_TYPES consumers).
 */
import type { StructureDefinition } from '@medplum/fhirtypes';
import condition from './Condition-diagnose.json';
import observation from './Observation-laborbefund.json';
import patient from './Patient-person.json';
import procedure from './Procedure-prozedur.json';
import medication from './MedicationStatement-medikation.json';
import encounter from './Encounter-fall.json';
import consent from './Consent-consent.json';

const REGISTRY: Record<string, StructureDefinition> = {
  Condition: condition as unknown as StructureDefinition,
  Observation: observation as unknown as StructureDefinition,
  Patient: patient as unknown as StructureDefinition,
  Procedure: procedure as unknown as StructureDefinition,
  MedicationStatement: medication as unknown as StructureDefinition,
  Encounter: encounter as unknown as StructureDefinition,
  Consent: consent as unknown as StructureDefinition,
};

export const BUNDLED_PROFILE_TYPES = Object.keys(REGISTRY) as readonly string[];

export function getProfileForType(resourceType: string): StructureDefinition | null {
  return REGISTRY[resourceType] ?? null;
}

// -----------------------------------------------------------------------
// Phase 36 / MII-EXT-12: lazy-load extension profiles from URL-keyed thunks.
// The REGISTRY value type is () => Promise<{ default: StructureDefinition }>
// (per extensions/index.ts post-Phase-36 shape). First call for a URL
// triggers the dynamic import; subsequent calls hit the module-scoped
// cache. Concurrent calls for the same URL share the same in-flight
// Promise (StrictMode-safe).
//
// Extension profiles are URL-keyed (NOT type-keyed) because each MII
// extension package ships multiple profiles of the same FHIR type (e.g.
// Onkologie has 5+ Condition profiles). URL keying keeps them distinct.
// The registry is mounted from src/quality/profiles/extensions/index.ts,
// which is regenerated by scripts/fetch-mii-profiles.mjs on npm install.
// The committed JSON is the authoritative copy — offline installs pass.
// -----------------------------------------------------------------------

import { REGISTRY as EXTENSION_REGISTRY } from './extensions/index';

export const BUNDLED_EXTENSION_PROFILE_URLS = Object.keys(
  EXTENSION_REGISTRY,
) as readonly string[];

const extensionProfileCache = new Map<string, StructureDefinition>();
const extensionProfileInFlight = new Map<
  string,
  Promise<StructureDefinition | null>
>();

export async function getExtensionProfileForUrl(
  canonicalUrl: string,
): Promise<StructureDefinition | null> {
  const cached = extensionProfileCache.get(canonicalUrl);
  if (cached !== undefined) return cached;

  const inFlight = extensionProfileInFlight.get(canonicalUrl);
  if (inFlight !== undefined) return inFlight;

  const loader = EXTENSION_REGISTRY[canonicalUrl];
  if (!loader) return null;

  const promise = loader()
    .then((mod) => {
      // Pitfall 1: dynamic JSON import returns { default: SD }, NOT SD.
      // Static imports are auto-unwrapped by Vite; dynamic imports are NOT.
      const sd = mod.default;
      extensionProfileCache.set(canonicalUrl, sd);
      extensionProfileInFlight.delete(canonicalUrl);
      return sd;
    })
    .catch((err) => {
      extensionProfileInFlight.delete(canonicalUrl);
      // Surface failure as null per ROADMAP "load on-demand" semantics;
      // logging at the boundary helps diagnose dev-time regressions.
      console.warn(
        `[extensions] failed to lazy-load ${canonicalUrl}: ${String(err)}`,
      );
      return null;
    });
  extensionProfileInFlight.set(canonicalUrl, promise);
  return promise;
}
